// -------------------------------------------------------------
// 
// File Name: F:\apparatlab2\fixed\calk\atan2_cordic_nw.v
// Created: 2023-01-16 23:59:55
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: atan2_cordic_nw
// Source Path: calk/CALC_MAGNITUDE_AND_PHASE_FIXED/atan2_cordic_nw
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module atan2_cordic_nw
          (clk,
           reset,
           enb,
           y_in,
           x_in,
           angle);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] y_in;  // sfix32_En27
  input   signed [31:0] x_in;  // sfix32_En27
  output  signed [31:0] angle;  // sfix32_En29


  wire signed [33:0] y_in_ext;  // sfix34_En27
  reg signed [33:0] y_in_reg_out_1;  // sfix34_En27
  wire y_in_msb;  // ufix1
  wire switch_compare_1;
  wire comp_zero;  // ufix1
  wire y_non_zero;  // ufix1
  reg  [0:30] y_non_zero_reg_reg;  // ufix1 [31]
  wire [0:30] y_non_zero_reg_reg_next;  // ufix1 [31]
  wire y_non_zero_p;  // ufix1
  wire signed [33:0] x_in_ext;  // sfix34_En27
  reg signed [33:0] x_in_reg_out_1;  // sfix34_En27
  wire x_in_msb;  // ufix1
  reg  [0:30] x_quad_adjust_reg_reg;  // ufix1 [31]
  wire [0:30] x_quad_adjust_reg_reg_next;  // ufix1 [31]
  wire x_quad_adjust_p;  // ufix1
  reg  [0:30] y_quad_adjust_reg_reg;  // ufix1 [31]
  wire [0:30] y_quad_adjust_reg_reg_next;  // ufix1 [31]
  wire y_quad_adjust_p;  // ufix1
  wire [2:0] x_y_adjust;  // ufix3
  wire signed [31:0] zero;  // sfix32_En29
  wire signed [31:0] onePi_1;  // sfix32_En29
  wire switch_compare_1_1;
  wire signed [34:0] y_in_reg_neg_cast;  // sfix35_En27
  wire signed [34:0] y_in_reg_neg_cast_1;  // sfix35_En27
  wire signed [33:0] y_in_reg_neg_1;  // sfix34_En27
  wire signed [33:0] y_pre_quadcorr_out;  // sfix34_En27
  reg signed [33:0] y0_p;  // sfix34_En27
  wire y0_p_msb;  // ufix1
  wire switch_compare_1_2;
  wire switch_compare_1_3;
  wire signed [34:0] x_in_reg_neg_cast;  // sfix35_En27
  wire signed [34:0] x_in_reg_neg_cast_1;  // sfix35_En27
  wire signed [33:0] x_in_reg_neg_1;  // sfix34_En27
  wire signed [33:0] x_pre_quadcorr_out;  // sfix34_En27
  reg signed [33:0] x0_p;  // sfix34_En27
  wire signed [33:0] y_temp1;  // sfix34_En27
  wire signed [33:0] y_temp_0_1_1;  // sfix34_En27
  wire signed [33:0] y1;  // sfix34_En27
  reg signed [33:0] y1_p;  // sfix34_En27
  wire y1_p_msb;  // ufix1
  wire switch_compare_1_4;
  wire switch_compare_1_5;
  wire signed [33:0] x_temp1;  // sfix34_En27
  wire signed [33:0] x_temp_0_1_1;  // sfix34_En27
  wire signed [33:0] x1;  // sfix34_En27
  reg signed [33:0] x1_p;  // sfix34_En27
  wire signed [33:0] x_shift2;  // sfix34_En27
  wire signed [33:0] y_temp2;  // sfix34_En27
  wire signed [33:0] y_temp_0_2_1;  // sfix34_En27
  wire signed [33:0] y2;  // sfix34_En27
  reg signed [33:0] y2_p;  // sfix34_En27
  wire y2_p_msb;  // ufix1
  wire switch_compare_1_6;
  wire switch_compare_1_7;
  wire signed [33:0] y_shift2;  // sfix34_En27
  wire signed [33:0] x_temp2;  // sfix34_En27
  wire signed [33:0] x_temp_0_2_1;  // sfix34_En27
  wire signed [33:0] x2;  // sfix34_En27
  reg signed [33:0] x2_p;  // sfix34_En27
  wire signed [33:0] x_shift3;  // sfix34_En27
  wire signed [33:0] y_temp3;  // sfix34_En27
  wire signed [33:0] y_temp_0_3_1;  // sfix34_En27
  wire signed [33:0] y3;  // sfix34_En27
  reg signed [33:0] y3_p;  // sfix34_En27
  wire y3_p_msb;  // ufix1
  wire switch_compare_1_8;
  wire switch_compare_1_9;
  wire signed [33:0] y_shift3;  // sfix34_En27
  wire signed [33:0] x_temp3;  // sfix34_En27
  wire signed [33:0] x_temp_0_3_1;  // sfix34_En27
  wire signed [33:0] x3;  // sfix34_En27
  reg signed [33:0] x3_p;  // sfix34_En27
  wire signed [33:0] x_shift4;  // sfix34_En27
  wire signed [33:0] y_temp4;  // sfix34_En27
  wire signed [33:0] y_temp_0_4_1;  // sfix34_En27
  wire signed [33:0] y4;  // sfix34_En27
  reg signed [33:0] y4_p;  // sfix34_En27
  wire y4_p_msb;  // ufix1
  wire switch_compare_1_10;
  wire switch_compare_1_11;
  wire signed [33:0] y_shift4;  // sfix34_En27
  wire signed [33:0] x_temp4;  // sfix34_En27
  wire signed [33:0] x_temp_0_4_1;  // sfix34_En27
  wire signed [33:0] x4;  // sfix34_En27
  reg signed [33:0] x4_p;  // sfix34_En27
  wire signed [33:0] x_shift5;  // sfix34_En27
  wire signed [33:0] y_temp5;  // sfix34_En27
  wire signed [33:0] y_temp_0_5_1;  // sfix34_En27
  wire signed [33:0] y5;  // sfix34_En27
  reg signed [33:0] y5_p;  // sfix34_En27
  wire y5_p_msb;  // ufix1
  wire switch_compare_1_12;
  wire switch_compare_1_13;
  wire signed [33:0] y_shift5;  // sfix34_En27
  wire signed [33:0] x_temp5;  // sfix34_En27
  wire signed [33:0] x_temp_0_5_1;  // sfix34_En27
  wire signed [33:0] x5;  // sfix34_En27
  reg signed [33:0] x5_p;  // sfix34_En27
  wire signed [33:0] x_shift6;  // sfix34_En27
  wire signed [33:0] y_temp6;  // sfix34_En27
  wire signed [33:0] y_temp_0_6_1;  // sfix34_En27
  wire signed [33:0] y6;  // sfix34_En27
  reg signed [33:0] y6_p;  // sfix34_En27
  wire y6_p_msb;  // ufix1
  wire switch_compare_1_14;
  wire switch_compare_1_15;
  wire signed [33:0] y_shift6;  // sfix34_En27
  wire signed [33:0] x_temp6;  // sfix34_En27
  wire signed [33:0] x_temp_0_6_1;  // sfix34_En27
  wire signed [33:0] x6;  // sfix34_En27
  reg signed [33:0] x6_p;  // sfix34_En27
  wire signed [33:0] x_shift7;  // sfix34_En27
  wire signed [33:0] y_temp7;  // sfix34_En27
  wire signed [33:0] y_temp_0_7_1;  // sfix34_En27
  wire signed [33:0] y7;  // sfix34_En27
  reg signed [33:0] y7_p;  // sfix34_En27
  wire y7_p_msb;  // ufix1
  wire switch_compare_1_16;
  wire switch_compare_1_17;
  wire signed [33:0] y_shift7;  // sfix34_En27
  wire signed [33:0] x_temp7;  // sfix34_En27
  wire signed [33:0] x_temp_0_7_1;  // sfix34_En27
  wire signed [33:0] x7;  // sfix34_En27
  reg signed [33:0] x7_p;  // sfix34_En27
  wire signed [33:0] x_shift8;  // sfix34_En27
  wire signed [33:0] y_temp8;  // sfix34_En27
  wire signed [33:0] y_temp_0_8_1;  // sfix34_En27
  wire signed [33:0] y8;  // sfix34_En27
  reg signed [33:0] y8_p;  // sfix34_En27
  wire y8_p_msb;  // ufix1
  wire switch_compare_1_18;
  wire switch_compare_1_19;
  wire signed [33:0] y_shift8;  // sfix34_En27
  wire signed [33:0] x_temp8;  // sfix34_En27
  wire signed [33:0] x_temp_0_8_1;  // sfix34_En27
  wire signed [33:0] x8;  // sfix34_En27
  reg signed [33:0] x8_p;  // sfix34_En27
  wire signed [33:0] x_shift9;  // sfix34_En27
  wire signed [33:0] y_temp9;  // sfix34_En27
  wire signed [33:0] y_temp_0_9_1;  // sfix34_En27
  wire signed [33:0] y9;  // sfix34_En27
  reg signed [33:0] y9_p;  // sfix34_En27
  wire y9_p_msb;  // ufix1
  wire switch_compare_1_20;
  wire switch_compare_1_21;
  wire signed [33:0] y_shift9;  // sfix34_En27
  wire signed [33:0] x_temp9;  // sfix34_En27
  wire signed [33:0] x_temp_0_9_1;  // sfix34_En27
  wire signed [33:0] x9;  // sfix34_En27
  reg signed [33:0] x9_p;  // sfix34_En27
  wire signed [33:0] x_shift10;  // sfix34_En27
  wire signed [33:0] y_temp10;  // sfix34_En27
  wire signed [33:0] y_temp_0_10_1;  // sfix34_En27
  wire signed [33:0] y10;  // sfix34_En27
  reg signed [33:0] y10_p;  // sfix34_En27
  wire y10_p_msb;  // ufix1
  wire switch_compare_1_22;
  wire switch_compare_1_23;
  wire signed [33:0] y_shift10;  // sfix34_En27
  wire signed [33:0] x_temp10;  // sfix34_En27
  wire signed [33:0] x_temp_0_10_1;  // sfix34_En27
  wire signed [33:0] x10;  // sfix34_En27
  reg signed [33:0] x10_p;  // sfix34_En27
  wire signed [33:0] x_shift11;  // sfix34_En27
  wire signed [33:0] y_temp11;  // sfix34_En27
  wire signed [33:0] y_temp_0_11_1;  // sfix34_En27
  wire signed [33:0] y11;  // sfix34_En27
  reg signed [33:0] y11_p;  // sfix34_En27
  wire y11_p_msb;  // ufix1
  wire switch_compare_1_24;
  wire switch_compare_1_25;
  wire signed [33:0] y_shift11;  // sfix34_En27
  wire signed [33:0] x_temp11;  // sfix34_En27
  wire signed [33:0] x_temp_0_11_1;  // sfix34_En27
  wire signed [33:0] x11;  // sfix34_En27
  reg signed [33:0] x11_p;  // sfix34_En27
  wire signed [33:0] x_shift12;  // sfix34_En27
  wire signed [33:0] y_temp12;  // sfix34_En27
  wire signed [33:0] y_temp_0_12_1;  // sfix34_En27
  wire signed [33:0] y12;  // sfix34_En27
  reg signed [33:0] y12_p;  // sfix34_En27
  wire y12_p_msb;  // ufix1
  wire switch_compare_1_26;
  wire switch_compare_1_27;
  wire signed [33:0] y_shift12;  // sfix34_En27
  wire signed [33:0] x_temp12;  // sfix34_En27
  wire signed [33:0] x_temp_0_12_1;  // sfix34_En27
  wire signed [33:0] x12;  // sfix34_En27
  reg signed [33:0] x12_p;  // sfix34_En27
  wire signed [33:0] x_shift13;  // sfix34_En27
  wire signed [33:0] y_temp13;  // sfix34_En27
  wire signed [33:0] y_temp_0_13_1;  // sfix34_En27
  wire signed [33:0] y13;  // sfix34_En27
  reg signed [33:0] y13_p;  // sfix34_En27
  wire y13_p_msb;  // ufix1
  wire switch_compare_1_28;
  wire switch_compare_1_29;
  wire signed [33:0] y_shift13;  // sfix34_En27
  wire signed [33:0] x_temp13;  // sfix34_En27
  wire signed [33:0] x_temp_0_13_1;  // sfix34_En27
  wire signed [33:0] x13;  // sfix34_En27
  reg signed [33:0] x13_p;  // sfix34_En27
  wire signed [33:0] x_shift14;  // sfix34_En27
  wire signed [33:0] y_temp14;  // sfix34_En27
  wire signed [33:0] y_temp_0_14_1;  // sfix34_En27
  wire signed [33:0] y14;  // sfix34_En27
  reg signed [33:0] y14_p;  // sfix34_En27
  wire y14_p_msb;  // ufix1
  wire switch_compare_1_30;
  wire switch_compare_1_31;
  wire signed [33:0] y_shift14;  // sfix34_En27
  wire signed [33:0] x_temp14;  // sfix34_En27
  wire signed [33:0] x_temp_0_14_1;  // sfix34_En27
  wire signed [33:0] x14;  // sfix34_En27
  reg signed [33:0] x14_p;  // sfix34_En27
  wire signed [33:0] x_shift15;  // sfix34_En27
  wire signed [33:0] y_temp15;  // sfix34_En27
  wire signed [33:0] y_temp_0_15_1;  // sfix34_En27
  wire signed [33:0] y15;  // sfix34_En27
  reg signed [33:0] y15_p;  // sfix34_En27
  wire y15_p_msb;  // ufix1
  wire switch_compare_1_32;
  wire switch_compare_1_33;
  wire signed [33:0] y_shift15;  // sfix34_En27
  wire signed [33:0] x_temp15;  // sfix34_En27
  wire signed [33:0] x_temp_0_15_1;  // sfix34_En27
  wire signed [33:0] x15;  // sfix34_En27
  reg signed [33:0] x15_p;  // sfix34_En27
  wire signed [33:0] x_shift16;  // sfix34_En27
  wire signed [33:0] y_temp16;  // sfix34_En27
  wire signed [33:0] y_temp_0_16_1;  // sfix34_En27
  wire signed [33:0] y16;  // sfix34_En27
  reg signed [33:0] y16_p;  // sfix34_En27
  wire y16_p_msb;  // ufix1
  wire switch_compare_1_34;
  wire switch_compare_1_35;
  wire signed [33:0] y_shift16;  // sfix34_En27
  wire signed [33:0] x_temp16;  // sfix34_En27
  wire signed [33:0] x_temp_0_16_1;  // sfix34_En27
  wire signed [33:0] x16;  // sfix34_En27
  reg signed [33:0] x16_p;  // sfix34_En27
  wire signed [33:0] x_shift17;  // sfix34_En27
  wire signed [33:0] y_temp17;  // sfix34_En27
  wire signed [33:0] y_temp_0_17_1;  // sfix34_En27
  wire signed [33:0] y17;  // sfix34_En27
  reg signed [33:0] y17_p;  // sfix34_En27
  wire y17_p_msb;  // ufix1
  wire switch_compare_1_36;
  wire switch_compare_1_37;
  wire signed [33:0] y_shift17;  // sfix34_En27
  wire signed [33:0] x_temp17;  // sfix34_En27
  wire signed [33:0] x_temp_0_17_1;  // sfix34_En27
  wire signed [33:0] x17;  // sfix34_En27
  reg signed [33:0] x17_p;  // sfix34_En27
  wire signed [33:0] x_shift18;  // sfix34_En27
  wire signed [33:0] y_temp18;  // sfix34_En27
  wire signed [33:0] y_temp_0_18_1;  // sfix34_En27
  wire signed [33:0] y18;  // sfix34_En27
  reg signed [33:0] y18_p;  // sfix34_En27
  wire y18_p_msb;  // ufix1
  wire switch_compare_1_38;
  wire switch_compare_1_39;
  wire signed [33:0] y_shift18;  // sfix34_En27
  wire signed [33:0] x_temp18;  // sfix34_En27
  wire signed [33:0] x_temp_0_18_1;  // sfix34_En27
  wire signed [33:0] x18;  // sfix34_En27
  reg signed [33:0] x18_p;  // sfix34_En27
  wire signed [33:0] x_shift19;  // sfix34_En27
  wire signed [33:0] y_temp19;  // sfix34_En27
  wire signed [33:0] y_temp_0_19_1;  // sfix34_En27
  wire signed [33:0] y19;  // sfix34_En27
  reg signed [33:0] y19_p;  // sfix34_En27
  wire y19_p_msb;  // ufix1
  wire switch_compare_1_40;
  wire switch_compare_1_41;
  wire signed [33:0] y_shift19;  // sfix34_En27
  wire signed [33:0] x_temp19;  // sfix34_En27
  wire signed [33:0] x_temp_0_19_1;  // sfix34_En27
  wire signed [33:0] x19;  // sfix34_En27
  reg signed [33:0] x19_p;  // sfix34_En27
  wire signed [33:0] x_shift20;  // sfix34_En27
  wire signed [33:0] y_temp20;  // sfix34_En27
  wire signed [33:0] y_temp_0_20_1;  // sfix34_En27
  wire signed [33:0] y20;  // sfix34_En27
  reg signed [33:0] y20_p;  // sfix34_En27
  wire y20_p_msb;  // ufix1
  wire switch_compare_1_42;
  wire switch_compare_1_43;
  wire signed [33:0] y_shift20;  // sfix34_En27
  wire signed [33:0] x_temp20;  // sfix34_En27
  wire signed [33:0] x_temp_0_20_1;  // sfix34_En27
  wire signed [33:0] x20;  // sfix34_En27
  reg signed [33:0] x20_p;  // sfix34_En27
  wire signed [33:0] x_shift21;  // sfix34_En27
  wire signed [33:0] y_temp21;  // sfix34_En27
  wire signed [33:0] y_temp_0_21_1;  // sfix34_En27
  wire signed [33:0] y21;  // sfix34_En27
  reg signed [33:0] y21_p;  // sfix34_En27
  wire y21_p_msb;  // ufix1
  wire switch_compare_1_44;
  wire switch_compare_1_45;
  wire signed [33:0] y_shift21;  // sfix34_En27
  wire signed [33:0] x_temp21;  // sfix34_En27
  wire signed [33:0] x_temp_0_21_1;  // sfix34_En27
  wire signed [33:0] x21;  // sfix34_En27
  reg signed [33:0] x21_p;  // sfix34_En27
  wire signed [33:0] x_shift22;  // sfix34_En27
  wire signed [33:0] y_temp22;  // sfix34_En27
  wire signed [33:0] y_temp_0_22_1;  // sfix34_En27
  wire signed [33:0] y22;  // sfix34_En27
  reg signed [33:0] y22_p;  // sfix34_En27
  wire y22_p_msb;  // ufix1
  wire switch_compare_1_46;
  wire switch_compare_1_47;
  wire signed [33:0] y_shift22;  // sfix34_En27
  wire signed [33:0] x_temp22;  // sfix34_En27
  wire signed [33:0] x_temp_0_22_1;  // sfix34_En27
  wire signed [33:0] x22;  // sfix34_En27
  reg signed [33:0] x22_p;  // sfix34_En27
  wire signed [33:0] x_shift23;  // sfix34_En27
  wire signed [33:0] y_temp23;  // sfix34_En27
  wire signed [33:0] y_temp_0_23_1;  // sfix34_En27
  wire signed [33:0] y23;  // sfix34_En27
  reg signed [33:0] y23_p;  // sfix34_En27
  wire y23_p_msb;  // ufix1
  wire switch_compare_1_48;
  wire switch_compare_1_49;
  wire signed [33:0] y_shift23;  // sfix34_En27
  wire signed [33:0] x_temp23;  // sfix34_En27
  wire signed [33:0] x_temp_0_23_1;  // sfix34_En27
  wire signed [33:0] x23;  // sfix34_En27
  reg signed [33:0] x23_p;  // sfix34_En27
  wire signed [33:0] x_shift24;  // sfix34_En27
  wire signed [33:0] y_temp24;  // sfix34_En27
  wire signed [33:0] y_temp_0_24_1;  // sfix34_En27
  wire signed [33:0] y24;  // sfix34_En27
  reg signed [33:0] y24_p;  // sfix34_En27
  wire y24_p_msb;  // ufix1
  wire switch_compare_1_50;
  wire switch_compare_1_51;
  wire signed [33:0] y_shift24;  // sfix34_En27
  wire signed [33:0] x_temp24;  // sfix34_En27
  wire signed [33:0] x_temp_0_24_1;  // sfix34_En27
  wire signed [33:0] x24;  // sfix34_En27
  reg signed [33:0] x24_p;  // sfix34_En27
  wire signed [33:0] x_shift25;  // sfix34_En27
  wire signed [33:0] y_temp25;  // sfix34_En27
  wire signed [33:0] y_temp_0_25_1;  // sfix34_En27
  wire signed [33:0] y25;  // sfix34_En27
  reg signed [33:0] y25_p;  // sfix34_En27
  wire y25_p_msb;  // ufix1
  wire switch_compare_1_52;
  wire switch_compare_1_53;
  wire signed [33:0] y_shift25;  // sfix34_En27
  wire signed [33:0] x_temp25;  // sfix34_En27
  wire signed [33:0] x_temp_0_25_1;  // sfix34_En27
  wire signed [33:0] x25;  // sfix34_En27
  reg signed [33:0] x25_p;  // sfix34_En27
  wire signed [33:0] x_shift26;  // sfix34_En27
  wire signed [33:0] y_temp26;  // sfix34_En27
  wire signed [33:0] y_temp_0_26_1;  // sfix34_En27
  wire signed [33:0] y26;  // sfix34_En27
  reg signed [33:0] y26_p;  // sfix34_En27
  wire y26_p_msb;  // ufix1
  wire switch_compare_1_54;
  wire switch_compare_1_55;
  wire signed [33:0] y_shift26;  // sfix34_En27
  wire signed [33:0] x_temp26;  // sfix34_En27
  wire signed [33:0] x_temp_0_26_1;  // sfix34_En27
  wire signed [33:0] x26;  // sfix34_En27
  reg signed [33:0] x26_p;  // sfix34_En27
  wire signed [33:0] x_shift27;  // sfix34_En27
  wire signed [33:0] y_temp27;  // sfix34_En27
  wire signed [33:0] y_temp_0_27_1;  // sfix34_En27
  wire signed [33:0] y27;  // sfix34_En27
  reg signed [33:0] y27_p;  // sfix34_En27
  wire y27_p_msb;  // ufix1
  wire switch_compare_1_56;
  wire switch_compare_1_57;
  wire signed [33:0] y_shift27;  // sfix34_En27
  wire signed [33:0] x_temp27;  // sfix34_En27
  wire signed [33:0] x_temp_0_27_1;  // sfix34_En27
  wire signed [33:0] x27;  // sfix34_En27
  reg signed [33:0] x27_p;  // sfix34_En27
  wire signed [33:0] x_shift28;  // sfix34_En27
  wire signed [33:0] y_temp28;  // sfix34_En27
  wire signed [33:0] y_temp_0_28_1;  // sfix34_En27
  wire signed [33:0] y28;  // sfix34_En27
  reg signed [33:0] y28_p;  // sfix34_En27
  wire y28_p_msb;  // ufix1
  wire switch_compare_1_58;
  wire switch_compare_1_59;
  wire signed [33:0] y_shift28;  // sfix34_En27
  wire signed [33:0] x_temp28;  // sfix34_En27
  wire signed [33:0] x_temp_0_28_1;  // sfix34_En27
  wire signed [33:0] x28;  // sfix34_En27
  reg signed [33:0] x28_p;  // sfix34_En27
  wire signed [33:0] x_shift29;  // sfix34_En27
  wire signed [33:0] y_temp29;  // sfix34_En27
  wire signed [33:0] y_temp_0_29_1;  // sfix34_En27
  wire signed [33:0] y29;  // sfix34_En27
  reg signed [33:0] y29_p;  // sfix34_En27
  wire y29_p_msb;  // ufix1
  wire switch_compare_1_60;
  wire switch_compare_1_61;
  wire switch_compare_1_62;
  wire switch_compare_1_63;
  wire switch_compare_1_64;
  wire switch_compare_1_65;
  wire switch_compare_1_66;
  wire switch_compare_1_67;
  wire switch_compare_1_68;
  wire switch_compare_1_69;
  wire switch_compare_1_70;
  wire switch_compare_1_71;
  wire switch_compare_1_72;
  wire switch_compare_1_73;
  wire switch_compare_1_74;
  wire switch_compare_1_75;
  wire switch_compare_1_76;
  wire switch_compare_1_77;
  wire switch_compare_1_78;
  wire switch_compare_1_79;
  wire switch_compare_1_80;
  wire switch_compare_1_81;
  wire switch_compare_1_82;
  wire switch_compare_1_83;
  wire switch_compare_1_84;
  wire switch_compare_1_85;
  wire switch_compare_1_86;
  wire switch_compare_1_87;
  wire switch_compare_1_88;
  wire switch_compare_1_89;
  wire signed [33:0] z0;  // sfix34_En29
  wire signed [33:0] lut_value_s1;  // sfix34_En29
  wire signed [33:0] lut_value_temp1;  // sfix34_En29
  wire signed [33:0] y_temp_0_1_2;  // sfix34_En29
  wire signed [33:0] z1;  // sfix34_En29
  reg signed [33:0] z1_p;  // sfix34_En29
  wire signed [33:0] lut_value_s2;  // sfix34_En29
  wire signed [33:0] lut_value_temp2;  // sfix34_En29
  wire signed [33:0] y_temp_0_2_2;  // sfix34_En29
  wire signed [33:0] z2;  // sfix34_En29
  reg signed [33:0] z2_p;  // sfix34_En29
  wire signed [33:0] lut_value_s3;  // sfix34_En29
  wire signed [33:0] lut_value_temp3;  // sfix34_En29
  wire signed [33:0] y_temp_0_3_2;  // sfix34_En29
  wire signed [33:0] z3;  // sfix34_En29
  reg signed [33:0] z3_p;  // sfix34_En29
  wire signed [33:0] lut_value_s4;  // sfix34_En29
  wire signed [33:0] lut_value_temp4;  // sfix34_En29
  wire signed [33:0] y_temp_0_4_2;  // sfix34_En29
  wire signed [33:0] z4;  // sfix34_En29
  reg signed [33:0] z4_p;  // sfix34_En29
  wire signed [33:0] lut_value_s5;  // sfix34_En29
  wire signed [33:0] lut_value_temp5;  // sfix34_En29
  wire signed [33:0] y_temp_0_5_2;  // sfix34_En29
  wire signed [33:0] z5;  // sfix34_En29
  reg signed [33:0] z5_p;  // sfix34_En29
  wire signed [33:0] lut_value_s6;  // sfix34_En29
  wire signed [33:0] lut_value_temp6;  // sfix34_En29
  wire signed [33:0] y_temp_0_6_2;  // sfix34_En29
  wire signed [33:0] z6;  // sfix34_En29
  reg signed [33:0] z6_p;  // sfix34_En29
  wire signed [33:0] lut_value_s7;  // sfix34_En29
  wire signed [33:0] lut_value_temp7;  // sfix34_En29
  wire signed [33:0] y_temp_0_7_2;  // sfix34_En29
  wire signed [33:0] z7;  // sfix34_En29
  reg signed [33:0] z7_p;  // sfix34_En29
  wire signed [33:0] lut_value_s8;  // sfix34_En29
  wire signed [33:0] lut_value_temp8;  // sfix34_En29
  wire signed [33:0] y_temp_0_8_2;  // sfix34_En29
  wire signed [33:0] z8;  // sfix34_En29
  reg signed [33:0] z8_p;  // sfix34_En29
  wire signed [33:0] lut_value_s9;  // sfix34_En29
  wire signed [33:0] lut_value_temp9;  // sfix34_En29
  wire signed [33:0] y_temp_0_9_2;  // sfix34_En29
  wire signed [33:0] z9;  // sfix34_En29
  reg signed [33:0] z9_p;  // sfix34_En29
  wire signed [33:0] lut_value_s10;  // sfix34_En29
  wire signed [33:0] lut_value_temp10;  // sfix34_En29
  wire signed [33:0] y_temp_0_10_2;  // sfix34_En29
  wire signed [33:0] z10;  // sfix34_En29
  reg signed [33:0] z10_p;  // sfix34_En29
  wire signed [33:0] lut_value_s11;  // sfix34_En29
  wire signed [33:0] lut_value_temp11;  // sfix34_En29
  wire signed [33:0] y_temp_0_11_2;  // sfix34_En29
  wire signed [33:0] z11;  // sfix34_En29
  reg signed [33:0] z11_p;  // sfix34_En29
  wire signed [33:0] lut_value_s12;  // sfix34_En29
  wire signed [33:0] lut_value_temp12;  // sfix34_En29
  wire signed [33:0] y_temp_0_12_2;  // sfix34_En29
  wire signed [33:0] z12;  // sfix34_En29
  reg signed [33:0] z12_p;  // sfix34_En29
  wire signed [33:0] lut_value_s13;  // sfix34_En29
  wire signed [33:0] lut_value_temp13;  // sfix34_En29
  wire signed [33:0] y_temp_0_13_2;  // sfix34_En29
  wire signed [33:0] z13;  // sfix34_En29
  reg signed [33:0] z13_p;  // sfix34_En29
  wire signed [33:0] lut_value_s14;  // sfix34_En29
  wire signed [33:0] lut_value_temp14;  // sfix34_En29
  wire signed [33:0] y_temp_0_14_2;  // sfix34_En29
  wire signed [33:0] z14;  // sfix34_En29
  reg signed [33:0] z14_p;  // sfix34_En29
  wire signed [33:0] lut_value_s15;  // sfix34_En29
  wire signed [33:0] lut_value_temp15;  // sfix34_En29
  wire signed [33:0] y_temp_0_15_2;  // sfix34_En29
  wire signed [33:0] z15;  // sfix34_En29
  reg signed [33:0] z15_p;  // sfix34_En29
  wire signed [33:0] lut_value_s16;  // sfix34_En29
  wire signed [33:0] lut_value_temp16;  // sfix34_En29
  wire signed [33:0] y_temp_0_16_2;  // sfix34_En29
  wire signed [33:0] z16;  // sfix34_En29
  reg signed [33:0] z16_p;  // sfix34_En29
  wire signed [33:0] lut_value_s17;  // sfix34_En29
  wire signed [33:0] lut_value_temp17;  // sfix34_En29
  wire signed [33:0] y_temp_0_17_2;  // sfix34_En29
  wire signed [33:0] z17;  // sfix34_En29
  reg signed [33:0] z17_p;  // sfix34_En29
  wire signed [33:0] lut_value_s18;  // sfix34_En29
  wire signed [33:0] lut_value_temp18;  // sfix34_En29
  wire signed [33:0] y_temp_0_18_2;  // sfix34_En29
  wire signed [33:0] z18;  // sfix34_En29
  reg signed [33:0] z18_p;  // sfix34_En29
  wire signed [33:0] lut_value_s19;  // sfix34_En29
  wire signed [33:0] lut_value_temp19;  // sfix34_En29
  wire signed [33:0] y_temp_0_19_2;  // sfix34_En29
  wire signed [33:0] z19;  // sfix34_En29
  reg signed [33:0] z19_p;  // sfix34_En29
  wire signed [33:0] lut_value_s20;  // sfix34_En29
  wire signed [33:0] lut_value_temp20;  // sfix34_En29
  wire signed [33:0] y_temp_0_20_2;  // sfix34_En29
  wire signed [33:0] z20;  // sfix34_En29
  reg signed [33:0] z20_p;  // sfix34_En29
  wire signed [33:0] lut_value_s21;  // sfix34_En29
  wire signed [33:0] lut_value_temp21;  // sfix34_En29
  wire signed [33:0] y_temp_0_21_2;  // sfix34_En29
  wire signed [33:0] z21;  // sfix34_En29
  reg signed [33:0] z21_p;  // sfix34_En29
  wire signed [33:0] lut_value_s22;  // sfix34_En29
  wire signed [33:0] lut_value_temp22;  // sfix34_En29
  wire signed [33:0] y_temp_0_22_2;  // sfix34_En29
  wire signed [33:0] z22;  // sfix34_En29
  reg signed [33:0] z22_p;  // sfix34_En29
  wire signed [33:0] lut_value_s23;  // sfix34_En29
  wire signed [33:0] lut_value_temp23;  // sfix34_En29
  wire signed [33:0] y_temp_0_23_2;  // sfix34_En29
  wire signed [33:0] z23;  // sfix34_En29
  reg signed [33:0] z23_p;  // sfix34_En29
  wire signed [33:0] lut_value_s24;  // sfix34_En29
  wire signed [33:0] lut_value_temp24;  // sfix34_En29
  wire signed [33:0] y_temp_0_24_2;  // sfix34_En29
  wire signed [33:0] z24;  // sfix34_En29
  reg signed [33:0] z24_p;  // sfix34_En29
  wire signed [33:0] lut_value_s25;  // sfix34_En29
  wire signed [33:0] lut_value_temp25;  // sfix34_En29
  wire signed [33:0] y_temp_0_25_2;  // sfix34_En29
  wire signed [33:0] z25;  // sfix34_En29
  reg signed [33:0] z25_p;  // sfix34_En29
  wire signed [33:0] lut_value_s26;  // sfix34_En29
  wire signed [33:0] lut_value_temp26;  // sfix34_En29
  wire signed [33:0] y_temp_0_26_2;  // sfix34_En29
  wire signed [33:0] z26;  // sfix34_En29
  reg signed [33:0] z26_p;  // sfix34_En29
  wire signed [33:0] lut_value_s27;  // sfix34_En29
  wire signed [33:0] lut_value_temp27;  // sfix34_En29
  wire signed [33:0] y_temp_0_27_2;  // sfix34_En29
  wire signed [33:0] z27;  // sfix34_En29
  reg signed [33:0] z27_p;  // sfix34_En29
  wire signed [33:0] lut_value_s28;  // sfix34_En29
  wire signed [33:0] lut_value_temp28;  // sfix34_En29
  wire signed [33:0] y_temp_0_28_2;  // sfix34_En29
  wire signed [33:0] z28;  // sfix34_En29
  reg signed [33:0] z28_p;  // sfix34_En29
  wire signed [33:0] lut_value_s29;  // sfix34_En29
  wire signed [33:0] lut_value_temp29;  // sfix34_En29
  wire signed [33:0] y_temp_0_29_2;  // sfix34_En29
  wire signed [33:0] z29;  // sfix34_En29
  reg signed [33:0] z29_p;  // sfix34_En29
  wire signed [33:0] lut_value_s30;  // sfix34_En29
  wire signed [33:0] lut_value_temp30;  // sfix34_En29
  wire signed [33:0] y_temp_0_30;  // sfix34_En29
  wire signed [33:0] z30;  // sfix34_En29
  reg signed [33:0] z30_p;  // sfix34_En29
  wire signed [31:0] z_out;  // sfix32_En29
  wire signed [32:0] z_temp3_cast;  // sfix33_En29
  wire signed [32:0] z_temp3_cast_1;  // sfix33_En29
  wire signed [31:0] z_temp3_1;  // sfix32_En29
  wire signed [31:0] z_temp2_1;  // sfix32_En29
  wire signed [31:0] z_temp1_1;  // sfix32_En29
  reg signed [31:0] z_out_adjust;  // sfix32_En29
  reg signed [31:0] angle_1;  // sfix32_En29


  assign y_in_ext = {{2{y_in[31]}}, y_in};



  always @(posedge clk or posedge reset)
    begin : y_in_reg_out_process
      if (reset == 1'b1) begin
        y_in_reg_out_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y_in_reg_out_1 <= y_in_ext;
        end
      end
    end



  assign y_in_msb = y_in_reg_out_1[33];



  assign switch_compare_1 = y_in_msb > 1'b0;



  assign comp_zero = y_in_reg_out_1 > 34'sh000000000;



  assign y_non_zero = (switch_compare_1 == 1'b0 ? comp_zero :
              y_in_msb);



  always @(posedge clk or posedge reset)
    begin : y_non_zero_reg_process
      if (reset == 1'b1) begin
        y_non_zero_reg_reg[0] <= 1'b0;
        y_non_zero_reg_reg[1] <= 1'b0;
        y_non_zero_reg_reg[2] <= 1'b0;
        y_non_zero_reg_reg[3] <= 1'b0;
        y_non_zero_reg_reg[4] <= 1'b0;
        y_non_zero_reg_reg[5] <= 1'b0;
        y_non_zero_reg_reg[6] <= 1'b0;
        y_non_zero_reg_reg[7] <= 1'b0;
        y_non_zero_reg_reg[8] <= 1'b0;
        y_non_zero_reg_reg[9] <= 1'b0;
        y_non_zero_reg_reg[10] <= 1'b0;
        y_non_zero_reg_reg[11] <= 1'b0;
        y_non_zero_reg_reg[12] <= 1'b0;
        y_non_zero_reg_reg[13] <= 1'b0;
        y_non_zero_reg_reg[14] <= 1'b0;
        y_non_zero_reg_reg[15] <= 1'b0;
        y_non_zero_reg_reg[16] <= 1'b0;
        y_non_zero_reg_reg[17] <= 1'b0;
        y_non_zero_reg_reg[18] <= 1'b0;
        y_non_zero_reg_reg[19] <= 1'b0;
        y_non_zero_reg_reg[20] <= 1'b0;
        y_non_zero_reg_reg[21] <= 1'b0;
        y_non_zero_reg_reg[22] <= 1'b0;
        y_non_zero_reg_reg[23] <= 1'b0;
        y_non_zero_reg_reg[24] <= 1'b0;
        y_non_zero_reg_reg[25] <= 1'b0;
        y_non_zero_reg_reg[26] <= 1'b0;
        y_non_zero_reg_reg[27] <= 1'b0;
        y_non_zero_reg_reg[28] <= 1'b0;
        y_non_zero_reg_reg[29] <= 1'b0;
        y_non_zero_reg_reg[30] <= 1'b0;
      end
      else begin
        if (enb) begin
          y_non_zero_reg_reg[0] <= y_non_zero_reg_reg_next[0];
          y_non_zero_reg_reg[1] <= y_non_zero_reg_reg_next[1];
          y_non_zero_reg_reg[2] <= y_non_zero_reg_reg_next[2];
          y_non_zero_reg_reg[3] <= y_non_zero_reg_reg_next[3];
          y_non_zero_reg_reg[4] <= y_non_zero_reg_reg_next[4];
          y_non_zero_reg_reg[5] <= y_non_zero_reg_reg_next[5];
          y_non_zero_reg_reg[6] <= y_non_zero_reg_reg_next[6];
          y_non_zero_reg_reg[7] <= y_non_zero_reg_reg_next[7];
          y_non_zero_reg_reg[8] <= y_non_zero_reg_reg_next[8];
          y_non_zero_reg_reg[9] <= y_non_zero_reg_reg_next[9];
          y_non_zero_reg_reg[10] <= y_non_zero_reg_reg_next[10];
          y_non_zero_reg_reg[11] <= y_non_zero_reg_reg_next[11];
          y_non_zero_reg_reg[12] <= y_non_zero_reg_reg_next[12];
          y_non_zero_reg_reg[13] <= y_non_zero_reg_reg_next[13];
          y_non_zero_reg_reg[14] <= y_non_zero_reg_reg_next[14];
          y_non_zero_reg_reg[15] <= y_non_zero_reg_reg_next[15];
          y_non_zero_reg_reg[16] <= y_non_zero_reg_reg_next[16];
          y_non_zero_reg_reg[17] <= y_non_zero_reg_reg_next[17];
          y_non_zero_reg_reg[18] <= y_non_zero_reg_reg_next[18];
          y_non_zero_reg_reg[19] <= y_non_zero_reg_reg_next[19];
          y_non_zero_reg_reg[20] <= y_non_zero_reg_reg_next[20];
          y_non_zero_reg_reg[21] <= y_non_zero_reg_reg_next[21];
          y_non_zero_reg_reg[22] <= y_non_zero_reg_reg_next[22];
          y_non_zero_reg_reg[23] <= y_non_zero_reg_reg_next[23];
          y_non_zero_reg_reg[24] <= y_non_zero_reg_reg_next[24];
          y_non_zero_reg_reg[25] <= y_non_zero_reg_reg_next[25];
          y_non_zero_reg_reg[26] <= y_non_zero_reg_reg_next[26];
          y_non_zero_reg_reg[27] <= y_non_zero_reg_reg_next[27];
          y_non_zero_reg_reg[28] <= y_non_zero_reg_reg_next[28];
          y_non_zero_reg_reg[29] <= y_non_zero_reg_reg_next[29];
          y_non_zero_reg_reg[30] <= y_non_zero_reg_reg_next[30];
        end
      end
    end

  assign y_non_zero_p = y_non_zero_reg_reg[30];
  assign y_non_zero_reg_reg_next[0] = y_non_zero;
  assign y_non_zero_reg_reg_next[1] = y_non_zero_reg_reg[0];
  assign y_non_zero_reg_reg_next[2] = y_non_zero_reg_reg[1];
  assign y_non_zero_reg_reg_next[3] = y_non_zero_reg_reg[2];
  assign y_non_zero_reg_reg_next[4] = y_non_zero_reg_reg[3];
  assign y_non_zero_reg_reg_next[5] = y_non_zero_reg_reg[4];
  assign y_non_zero_reg_reg_next[6] = y_non_zero_reg_reg[5];
  assign y_non_zero_reg_reg_next[7] = y_non_zero_reg_reg[6];
  assign y_non_zero_reg_reg_next[8] = y_non_zero_reg_reg[7];
  assign y_non_zero_reg_reg_next[9] = y_non_zero_reg_reg[8];
  assign y_non_zero_reg_reg_next[10] = y_non_zero_reg_reg[9];
  assign y_non_zero_reg_reg_next[11] = y_non_zero_reg_reg[10];
  assign y_non_zero_reg_reg_next[12] = y_non_zero_reg_reg[11];
  assign y_non_zero_reg_reg_next[13] = y_non_zero_reg_reg[12];
  assign y_non_zero_reg_reg_next[14] = y_non_zero_reg_reg[13];
  assign y_non_zero_reg_reg_next[15] = y_non_zero_reg_reg[14];
  assign y_non_zero_reg_reg_next[16] = y_non_zero_reg_reg[15];
  assign y_non_zero_reg_reg_next[17] = y_non_zero_reg_reg[16];
  assign y_non_zero_reg_reg_next[18] = y_non_zero_reg_reg[17];
  assign y_non_zero_reg_reg_next[19] = y_non_zero_reg_reg[18];
  assign y_non_zero_reg_reg_next[20] = y_non_zero_reg_reg[19];
  assign y_non_zero_reg_reg_next[21] = y_non_zero_reg_reg[20];
  assign y_non_zero_reg_reg_next[22] = y_non_zero_reg_reg[21];
  assign y_non_zero_reg_reg_next[23] = y_non_zero_reg_reg[22];
  assign y_non_zero_reg_reg_next[24] = y_non_zero_reg_reg[23];
  assign y_non_zero_reg_reg_next[25] = y_non_zero_reg_reg[24];
  assign y_non_zero_reg_reg_next[26] = y_non_zero_reg_reg[25];
  assign y_non_zero_reg_reg_next[27] = y_non_zero_reg_reg[26];
  assign y_non_zero_reg_reg_next[28] = y_non_zero_reg_reg[27];
  assign y_non_zero_reg_reg_next[29] = y_non_zero_reg_reg[28];
  assign y_non_zero_reg_reg_next[30] = y_non_zero_reg_reg[29];



  assign x_in_ext = {{2{x_in[31]}}, x_in};



  always @(posedge clk or posedge reset)
    begin : x_in_reg_out_process
      if (reset == 1'b1) begin
        x_in_reg_out_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x_in_reg_out_1 <= x_in_ext;
        end
      end
    end



  assign x_in_msb = x_in_reg_out_1[33];



  always @(posedge clk or posedge reset)
    begin : x_quad_adjust_reg_process
      if (reset == 1'b1) begin
        x_quad_adjust_reg_reg[0] <= 1'b0;
        x_quad_adjust_reg_reg[1] <= 1'b0;
        x_quad_adjust_reg_reg[2] <= 1'b0;
        x_quad_adjust_reg_reg[3] <= 1'b0;
        x_quad_adjust_reg_reg[4] <= 1'b0;
        x_quad_adjust_reg_reg[5] <= 1'b0;
        x_quad_adjust_reg_reg[6] <= 1'b0;
        x_quad_adjust_reg_reg[7] <= 1'b0;
        x_quad_adjust_reg_reg[8] <= 1'b0;
        x_quad_adjust_reg_reg[9] <= 1'b0;
        x_quad_adjust_reg_reg[10] <= 1'b0;
        x_quad_adjust_reg_reg[11] <= 1'b0;
        x_quad_adjust_reg_reg[12] <= 1'b0;
        x_quad_adjust_reg_reg[13] <= 1'b0;
        x_quad_adjust_reg_reg[14] <= 1'b0;
        x_quad_adjust_reg_reg[15] <= 1'b0;
        x_quad_adjust_reg_reg[16] <= 1'b0;
        x_quad_adjust_reg_reg[17] <= 1'b0;
        x_quad_adjust_reg_reg[18] <= 1'b0;
        x_quad_adjust_reg_reg[19] <= 1'b0;
        x_quad_adjust_reg_reg[20] <= 1'b0;
        x_quad_adjust_reg_reg[21] <= 1'b0;
        x_quad_adjust_reg_reg[22] <= 1'b0;
        x_quad_adjust_reg_reg[23] <= 1'b0;
        x_quad_adjust_reg_reg[24] <= 1'b0;
        x_quad_adjust_reg_reg[25] <= 1'b0;
        x_quad_adjust_reg_reg[26] <= 1'b0;
        x_quad_adjust_reg_reg[27] <= 1'b0;
        x_quad_adjust_reg_reg[28] <= 1'b0;
        x_quad_adjust_reg_reg[29] <= 1'b0;
        x_quad_adjust_reg_reg[30] <= 1'b0;
      end
      else begin
        if (enb) begin
          x_quad_adjust_reg_reg[0] <= x_quad_adjust_reg_reg_next[0];
          x_quad_adjust_reg_reg[1] <= x_quad_adjust_reg_reg_next[1];
          x_quad_adjust_reg_reg[2] <= x_quad_adjust_reg_reg_next[2];
          x_quad_adjust_reg_reg[3] <= x_quad_adjust_reg_reg_next[3];
          x_quad_adjust_reg_reg[4] <= x_quad_adjust_reg_reg_next[4];
          x_quad_adjust_reg_reg[5] <= x_quad_adjust_reg_reg_next[5];
          x_quad_adjust_reg_reg[6] <= x_quad_adjust_reg_reg_next[6];
          x_quad_adjust_reg_reg[7] <= x_quad_adjust_reg_reg_next[7];
          x_quad_adjust_reg_reg[8] <= x_quad_adjust_reg_reg_next[8];
          x_quad_adjust_reg_reg[9] <= x_quad_adjust_reg_reg_next[9];
          x_quad_adjust_reg_reg[10] <= x_quad_adjust_reg_reg_next[10];
          x_quad_adjust_reg_reg[11] <= x_quad_adjust_reg_reg_next[11];
          x_quad_adjust_reg_reg[12] <= x_quad_adjust_reg_reg_next[12];
          x_quad_adjust_reg_reg[13] <= x_quad_adjust_reg_reg_next[13];
          x_quad_adjust_reg_reg[14] <= x_quad_adjust_reg_reg_next[14];
          x_quad_adjust_reg_reg[15] <= x_quad_adjust_reg_reg_next[15];
          x_quad_adjust_reg_reg[16] <= x_quad_adjust_reg_reg_next[16];
          x_quad_adjust_reg_reg[17] <= x_quad_adjust_reg_reg_next[17];
          x_quad_adjust_reg_reg[18] <= x_quad_adjust_reg_reg_next[18];
          x_quad_adjust_reg_reg[19] <= x_quad_adjust_reg_reg_next[19];
          x_quad_adjust_reg_reg[20] <= x_quad_adjust_reg_reg_next[20];
          x_quad_adjust_reg_reg[21] <= x_quad_adjust_reg_reg_next[21];
          x_quad_adjust_reg_reg[22] <= x_quad_adjust_reg_reg_next[22];
          x_quad_adjust_reg_reg[23] <= x_quad_adjust_reg_reg_next[23];
          x_quad_adjust_reg_reg[24] <= x_quad_adjust_reg_reg_next[24];
          x_quad_adjust_reg_reg[25] <= x_quad_adjust_reg_reg_next[25];
          x_quad_adjust_reg_reg[26] <= x_quad_adjust_reg_reg_next[26];
          x_quad_adjust_reg_reg[27] <= x_quad_adjust_reg_reg_next[27];
          x_quad_adjust_reg_reg[28] <= x_quad_adjust_reg_reg_next[28];
          x_quad_adjust_reg_reg[29] <= x_quad_adjust_reg_reg_next[29];
          x_quad_adjust_reg_reg[30] <= x_quad_adjust_reg_reg_next[30];
        end
      end
    end

  assign x_quad_adjust_p = x_quad_adjust_reg_reg[30];
  assign x_quad_adjust_reg_reg_next[0] = x_in_msb;
  assign x_quad_adjust_reg_reg_next[1] = x_quad_adjust_reg_reg[0];
  assign x_quad_adjust_reg_reg_next[2] = x_quad_adjust_reg_reg[1];
  assign x_quad_adjust_reg_reg_next[3] = x_quad_adjust_reg_reg[2];
  assign x_quad_adjust_reg_reg_next[4] = x_quad_adjust_reg_reg[3];
  assign x_quad_adjust_reg_reg_next[5] = x_quad_adjust_reg_reg[4];
  assign x_quad_adjust_reg_reg_next[6] = x_quad_adjust_reg_reg[5];
  assign x_quad_adjust_reg_reg_next[7] = x_quad_adjust_reg_reg[6];
  assign x_quad_adjust_reg_reg_next[8] = x_quad_adjust_reg_reg[7];
  assign x_quad_adjust_reg_reg_next[9] = x_quad_adjust_reg_reg[8];
  assign x_quad_adjust_reg_reg_next[10] = x_quad_adjust_reg_reg[9];
  assign x_quad_adjust_reg_reg_next[11] = x_quad_adjust_reg_reg[10];
  assign x_quad_adjust_reg_reg_next[12] = x_quad_adjust_reg_reg[11];
  assign x_quad_adjust_reg_reg_next[13] = x_quad_adjust_reg_reg[12];
  assign x_quad_adjust_reg_reg_next[14] = x_quad_adjust_reg_reg[13];
  assign x_quad_adjust_reg_reg_next[15] = x_quad_adjust_reg_reg[14];
  assign x_quad_adjust_reg_reg_next[16] = x_quad_adjust_reg_reg[15];
  assign x_quad_adjust_reg_reg_next[17] = x_quad_adjust_reg_reg[16];
  assign x_quad_adjust_reg_reg_next[18] = x_quad_adjust_reg_reg[17];
  assign x_quad_adjust_reg_reg_next[19] = x_quad_adjust_reg_reg[18];
  assign x_quad_adjust_reg_reg_next[20] = x_quad_adjust_reg_reg[19];
  assign x_quad_adjust_reg_reg_next[21] = x_quad_adjust_reg_reg[20];
  assign x_quad_adjust_reg_reg_next[22] = x_quad_adjust_reg_reg[21];
  assign x_quad_adjust_reg_reg_next[23] = x_quad_adjust_reg_reg[22];
  assign x_quad_adjust_reg_reg_next[24] = x_quad_adjust_reg_reg[23];
  assign x_quad_adjust_reg_reg_next[25] = x_quad_adjust_reg_reg[24];
  assign x_quad_adjust_reg_reg_next[26] = x_quad_adjust_reg_reg[25];
  assign x_quad_adjust_reg_reg_next[27] = x_quad_adjust_reg_reg[26];
  assign x_quad_adjust_reg_reg_next[28] = x_quad_adjust_reg_reg[27];
  assign x_quad_adjust_reg_reg_next[29] = x_quad_adjust_reg_reg[28];
  assign x_quad_adjust_reg_reg_next[30] = x_quad_adjust_reg_reg[29];



  always @(posedge clk or posedge reset)
    begin : y_quad_adjust_reg_process
      if (reset == 1'b1) begin
        y_quad_adjust_reg_reg[0] <= 1'b0;
        y_quad_adjust_reg_reg[1] <= 1'b0;
        y_quad_adjust_reg_reg[2] <= 1'b0;
        y_quad_adjust_reg_reg[3] <= 1'b0;
        y_quad_adjust_reg_reg[4] <= 1'b0;
        y_quad_adjust_reg_reg[5] <= 1'b0;
        y_quad_adjust_reg_reg[6] <= 1'b0;
        y_quad_adjust_reg_reg[7] <= 1'b0;
        y_quad_adjust_reg_reg[8] <= 1'b0;
        y_quad_adjust_reg_reg[9] <= 1'b0;
        y_quad_adjust_reg_reg[10] <= 1'b0;
        y_quad_adjust_reg_reg[11] <= 1'b0;
        y_quad_adjust_reg_reg[12] <= 1'b0;
        y_quad_adjust_reg_reg[13] <= 1'b0;
        y_quad_adjust_reg_reg[14] <= 1'b0;
        y_quad_adjust_reg_reg[15] <= 1'b0;
        y_quad_adjust_reg_reg[16] <= 1'b0;
        y_quad_adjust_reg_reg[17] <= 1'b0;
        y_quad_adjust_reg_reg[18] <= 1'b0;
        y_quad_adjust_reg_reg[19] <= 1'b0;
        y_quad_adjust_reg_reg[20] <= 1'b0;
        y_quad_adjust_reg_reg[21] <= 1'b0;
        y_quad_adjust_reg_reg[22] <= 1'b0;
        y_quad_adjust_reg_reg[23] <= 1'b0;
        y_quad_adjust_reg_reg[24] <= 1'b0;
        y_quad_adjust_reg_reg[25] <= 1'b0;
        y_quad_adjust_reg_reg[26] <= 1'b0;
        y_quad_adjust_reg_reg[27] <= 1'b0;
        y_quad_adjust_reg_reg[28] <= 1'b0;
        y_quad_adjust_reg_reg[29] <= 1'b0;
        y_quad_adjust_reg_reg[30] <= 1'b0;
      end
      else begin
        if (enb) begin
          y_quad_adjust_reg_reg[0] <= y_quad_adjust_reg_reg_next[0];
          y_quad_adjust_reg_reg[1] <= y_quad_adjust_reg_reg_next[1];
          y_quad_adjust_reg_reg[2] <= y_quad_adjust_reg_reg_next[2];
          y_quad_adjust_reg_reg[3] <= y_quad_adjust_reg_reg_next[3];
          y_quad_adjust_reg_reg[4] <= y_quad_adjust_reg_reg_next[4];
          y_quad_adjust_reg_reg[5] <= y_quad_adjust_reg_reg_next[5];
          y_quad_adjust_reg_reg[6] <= y_quad_adjust_reg_reg_next[6];
          y_quad_adjust_reg_reg[7] <= y_quad_adjust_reg_reg_next[7];
          y_quad_adjust_reg_reg[8] <= y_quad_adjust_reg_reg_next[8];
          y_quad_adjust_reg_reg[9] <= y_quad_adjust_reg_reg_next[9];
          y_quad_adjust_reg_reg[10] <= y_quad_adjust_reg_reg_next[10];
          y_quad_adjust_reg_reg[11] <= y_quad_adjust_reg_reg_next[11];
          y_quad_adjust_reg_reg[12] <= y_quad_adjust_reg_reg_next[12];
          y_quad_adjust_reg_reg[13] <= y_quad_adjust_reg_reg_next[13];
          y_quad_adjust_reg_reg[14] <= y_quad_adjust_reg_reg_next[14];
          y_quad_adjust_reg_reg[15] <= y_quad_adjust_reg_reg_next[15];
          y_quad_adjust_reg_reg[16] <= y_quad_adjust_reg_reg_next[16];
          y_quad_adjust_reg_reg[17] <= y_quad_adjust_reg_reg_next[17];
          y_quad_adjust_reg_reg[18] <= y_quad_adjust_reg_reg_next[18];
          y_quad_adjust_reg_reg[19] <= y_quad_adjust_reg_reg_next[19];
          y_quad_adjust_reg_reg[20] <= y_quad_adjust_reg_reg_next[20];
          y_quad_adjust_reg_reg[21] <= y_quad_adjust_reg_reg_next[21];
          y_quad_adjust_reg_reg[22] <= y_quad_adjust_reg_reg_next[22];
          y_quad_adjust_reg_reg[23] <= y_quad_adjust_reg_reg_next[23];
          y_quad_adjust_reg_reg[24] <= y_quad_adjust_reg_reg_next[24];
          y_quad_adjust_reg_reg[25] <= y_quad_adjust_reg_reg_next[25];
          y_quad_adjust_reg_reg[26] <= y_quad_adjust_reg_reg_next[26];
          y_quad_adjust_reg_reg[27] <= y_quad_adjust_reg_reg_next[27];
          y_quad_adjust_reg_reg[28] <= y_quad_adjust_reg_reg_next[28];
          y_quad_adjust_reg_reg[29] <= y_quad_adjust_reg_reg_next[29];
          y_quad_adjust_reg_reg[30] <= y_quad_adjust_reg_reg_next[30];
        end
      end
    end

  assign y_quad_adjust_p = y_quad_adjust_reg_reg[30];
  assign y_quad_adjust_reg_reg_next[0] = y_in_msb;
  assign y_quad_adjust_reg_reg_next[1] = y_quad_adjust_reg_reg[0];
  assign y_quad_adjust_reg_reg_next[2] = y_quad_adjust_reg_reg[1];
  assign y_quad_adjust_reg_reg_next[3] = y_quad_adjust_reg_reg[2];
  assign y_quad_adjust_reg_reg_next[4] = y_quad_adjust_reg_reg[3];
  assign y_quad_adjust_reg_reg_next[5] = y_quad_adjust_reg_reg[4];
  assign y_quad_adjust_reg_reg_next[6] = y_quad_adjust_reg_reg[5];
  assign y_quad_adjust_reg_reg_next[7] = y_quad_adjust_reg_reg[6];
  assign y_quad_adjust_reg_reg_next[8] = y_quad_adjust_reg_reg[7];
  assign y_quad_adjust_reg_reg_next[9] = y_quad_adjust_reg_reg[8];
  assign y_quad_adjust_reg_reg_next[10] = y_quad_adjust_reg_reg[9];
  assign y_quad_adjust_reg_reg_next[11] = y_quad_adjust_reg_reg[10];
  assign y_quad_adjust_reg_reg_next[12] = y_quad_adjust_reg_reg[11];
  assign y_quad_adjust_reg_reg_next[13] = y_quad_adjust_reg_reg[12];
  assign y_quad_adjust_reg_reg_next[14] = y_quad_adjust_reg_reg[13];
  assign y_quad_adjust_reg_reg_next[15] = y_quad_adjust_reg_reg[14];
  assign y_quad_adjust_reg_reg_next[16] = y_quad_adjust_reg_reg[15];
  assign y_quad_adjust_reg_reg_next[17] = y_quad_adjust_reg_reg[16];
  assign y_quad_adjust_reg_reg_next[18] = y_quad_adjust_reg_reg[17];
  assign y_quad_adjust_reg_reg_next[19] = y_quad_adjust_reg_reg[18];
  assign y_quad_adjust_reg_reg_next[20] = y_quad_adjust_reg_reg[19];
  assign y_quad_adjust_reg_reg_next[21] = y_quad_adjust_reg_reg[20];
  assign y_quad_adjust_reg_reg_next[22] = y_quad_adjust_reg_reg[21];
  assign y_quad_adjust_reg_reg_next[23] = y_quad_adjust_reg_reg[22];
  assign y_quad_adjust_reg_reg_next[24] = y_quad_adjust_reg_reg[23];
  assign y_quad_adjust_reg_reg_next[25] = y_quad_adjust_reg_reg[24];
  assign y_quad_adjust_reg_reg_next[26] = y_quad_adjust_reg_reg[25];
  assign y_quad_adjust_reg_reg_next[27] = y_quad_adjust_reg_reg[26];
  assign y_quad_adjust_reg_reg_next[28] = y_quad_adjust_reg_reg[27];
  assign y_quad_adjust_reg_reg_next[29] = y_quad_adjust_reg_reg[28];
  assign y_quad_adjust_reg_reg_next[30] = y_quad_adjust_reg_reg[29];



  assign x_y_adjust = {y_non_zero_p, x_quad_adjust_p, y_quad_adjust_p};



  assign zero = 32'sb00000000000000000000000000000000;



  assign onePi_1 = 32'sb01100100100001111110110101010001;



  assign switch_compare_1_1 = y_in_msb > 1'b0;



  assign y_in_reg_neg_cast = {y_in_reg_out_1[33], y_in_reg_out_1};
  assign y_in_reg_neg_cast_1 =  - (y_in_reg_neg_cast);
  assign y_in_reg_neg_1 = y_in_reg_neg_cast_1[33:0];



  assign y_pre_quadcorr_out = (switch_compare_1_1 == 1'b0 ? y_in_reg_out_1 :
              y_in_reg_neg_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : y_pre_quadcorr_out_reg_process
      if (reset == 1'b1) begin
        y0_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y0_p <= y_pre_quadcorr_out;
        end
      end
    end



  assign y0_p_msb = y0_p[33];



  assign switch_compare_1_2 = y0_p_msb > 1'b0;



  assign switch_compare_1_3 = x_in_msb > 1'b0;



  assign x_in_reg_neg_cast = {x_in_reg_out_1[33], x_in_reg_out_1};
  assign x_in_reg_neg_cast_1 =  - (x_in_reg_neg_cast);
  assign x_in_reg_neg_1 = x_in_reg_neg_cast_1[33:0];



  assign x_pre_quadcorr_out = (switch_compare_1_3 == 1'b0 ? x_in_reg_out_1 :
              x_in_reg_neg_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_pre_quadcorr_out_reg_process
      if (reset == 1'b1) begin
        x0_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x0_p <= x_pre_quadcorr_out;
        end
      end
    end



  assign y_temp1 = y0_p - x0_p;



  assign y_temp_0_1_1 = y0_p + x0_p;



  assign y1 = (switch_compare_1_2 == 1'b0 ? y_temp1 :
              y_temp_0_1_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_process
      if (reset == 1'b1) begin
        y1_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y1_p <= y1;
        end
      end
    end



  assign y1_p_msb = y1_p[33];



  assign switch_compare_1_4 = y1_p_msb > 1'b0;



  assign switch_compare_1_5 = y0_p_msb > 1'b0;



  assign x_temp1 = x0_p + y0_p;



  assign x_temp_0_1_1 = x0_p - y0_p;



  assign x1 = (switch_compare_1_5 == 1'b0 ? x_temp1 :
              x_temp_0_1_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_process
      if (reset == 1'b1) begin
        x1_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x1_p <= x1;
        end
      end
    end



  assign x_shift2 = x1_p >>> 8'd1;



  assign y_temp2 = y1_p - x_shift2;



  assign y_temp_0_2_1 = y1_p + x_shift2;



  assign y2 = (switch_compare_1_4 == 1'b0 ? y_temp2 :
              y_temp_0_2_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_1_process
      if (reset == 1'b1) begin
        y2_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y2_p <= y2;
        end
      end
    end



  assign y2_p_msb = y2_p[33];



  assign switch_compare_1_6 = y2_p_msb > 1'b0;



  assign switch_compare_1_7 = y1_p_msb > 1'b0;



  assign y_shift2 = y1_p >>> 8'd1;



  assign x_temp2 = x1_p + y_shift2;



  assign x_temp_0_2_1 = x1_p - y_shift2;



  assign x2 = (switch_compare_1_7 == 1'b0 ? x_temp2 :
              x_temp_0_2_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_1_process
      if (reset == 1'b1) begin
        x2_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x2_p <= x2;
        end
      end
    end



  assign x_shift3 = x2_p >>> 8'd2;



  assign y_temp3 = y2_p - x_shift3;



  assign y_temp_0_3_1 = y2_p + x_shift3;



  assign y3 = (switch_compare_1_6 == 1'b0 ? y_temp3 :
              y_temp_0_3_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_2_process
      if (reset == 1'b1) begin
        y3_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y3_p <= y3;
        end
      end
    end



  assign y3_p_msb = y3_p[33];



  assign switch_compare_1_8 = y3_p_msb > 1'b0;



  assign switch_compare_1_9 = y2_p_msb > 1'b0;



  assign y_shift3 = y2_p >>> 8'd2;



  assign x_temp3 = x2_p + y_shift3;



  assign x_temp_0_3_1 = x2_p - y_shift3;



  assign x3 = (switch_compare_1_9 == 1'b0 ? x_temp3 :
              x_temp_0_3_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_2_process
      if (reset == 1'b1) begin
        x3_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x3_p <= x3;
        end
      end
    end



  assign x_shift4 = x3_p >>> 8'd3;



  assign y_temp4 = y3_p - x_shift4;



  assign y_temp_0_4_1 = y3_p + x_shift4;



  assign y4 = (switch_compare_1_8 == 1'b0 ? y_temp4 :
              y_temp_0_4_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_3_process
      if (reset == 1'b1) begin
        y4_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y4_p <= y4;
        end
      end
    end



  assign y4_p_msb = y4_p[33];



  assign switch_compare_1_10 = y4_p_msb > 1'b0;



  assign switch_compare_1_11 = y3_p_msb > 1'b0;



  assign y_shift4 = y3_p >>> 8'd3;



  assign x_temp4 = x3_p + y_shift4;



  assign x_temp_0_4_1 = x3_p - y_shift4;



  assign x4 = (switch_compare_1_11 == 1'b0 ? x_temp4 :
              x_temp_0_4_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_3_process
      if (reset == 1'b1) begin
        x4_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x4_p <= x4;
        end
      end
    end



  assign x_shift5 = x4_p >>> 8'd4;



  assign y_temp5 = y4_p - x_shift5;



  assign y_temp_0_5_1 = y4_p + x_shift5;



  assign y5 = (switch_compare_1_10 == 1'b0 ? y_temp5 :
              y_temp_0_5_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_4_process
      if (reset == 1'b1) begin
        y5_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y5_p <= y5;
        end
      end
    end



  assign y5_p_msb = y5_p[33];



  assign switch_compare_1_12 = y5_p_msb > 1'b0;



  assign switch_compare_1_13 = y4_p_msb > 1'b0;



  assign y_shift5 = y4_p >>> 8'd4;



  assign x_temp5 = x4_p + y_shift5;



  assign x_temp_0_5_1 = x4_p - y_shift5;



  assign x5 = (switch_compare_1_13 == 1'b0 ? x_temp5 :
              x_temp_0_5_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_4_process
      if (reset == 1'b1) begin
        x5_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x5_p <= x5;
        end
      end
    end



  assign x_shift6 = x5_p >>> 8'd5;



  assign y_temp6 = y5_p - x_shift6;



  assign y_temp_0_6_1 = y5_p + x_shift6;



  assign y6 = (switch_compare_1_12 == 1'b0 ? y_temp6 :
              y_temp_0_6_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_5_process
      if (reset == 1'b1) begin
        y6_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y6_p <= y6;
        end
      end
    end



  assign y6_p_msb = y6_p[33];



  assign switch_compare_1_14 = y6_p_msb > 1'b0;



  assign switch_compare_1_15 = y5_p_msb > 1'b0;



  assign y_shift6 = y5_p >>> 8'd5;



  assign x_temp6 = x5_p + y_shift6;



  assign x_temp_0_6_1 = x5_p - y_shift6;



  assign x6 = (switch_compare_1_15 == 1'b0 ? x_temp6 :
              x_temp_0_6_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_5_process
      if (reset == 1'b1) begin
        x6_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x6_p <= x6;
        end
      end
    end



  assign x_shift7 = x6_p >>> 8'd6;



  assign y_temp7 = y6_p - x_shift7;



  assign y_temp_0_7_1 = y6_p + x_shift7;



  assign y7 = (switch_compare_1_14 == 1'b0 ? y_temp7 :
              y_temp_0_7_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_6_process
      if (reset == 1'b1) begin
        y7_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y7_p <= y7;
        end
      end
    end



  assign y7_p_msb = y7_p[33];



  assign switch_compare_1_16 = y7_p_msb > 1'b0;



  assign switch_compare_1_17 = y6_p_msb > 1'b0;



  assign y_shift7 = y6_p >>> 8'd6;



  assign x_temp7 = x6_p + y_shift7;



  assign x_temp_0_7_1 = x6_p - y_shift7;



  assign x7 = (switch_compare_1_17 == 1'b0 ? x_temp7 :
              x_temp_0_7_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_6_process
      if (reset == 1'b1) begin
        x7_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x7_p <= x7;
        end
      end
    end



  assign x_shift8 = x7_p >>> 8'd7;



  assign y_temp8 = y7_p - x_shift8;



  assign y_temp_0_8_1 = y7_p + x_shift8;



  assign y8 = (switch_compare_1_16 == 1'b0 ? y_temp8 :
              y_temp_0_8_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_7_process
      if (reset == 1'b1) begin
        y8_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y8_p <= y8;
        end
      end
    end



  assign y8_p_msb = y8_p[33];



  assign switch_compare_1_18 = y8_p_msb > 1'b0;



  assign switch_compare_1_19 = y7_p_msb > 1'b0;



  assign y_shift8 = y7_p >>> 8'd7;



  assign x_temp8 = x7_p + y_shift8;



  assign x_temp_0_8_1 = x7_p - y_shift8;



  assign x8 = (switch_compare_1_19 == 1'b0 ? x_temp8 :
              x_temp_0_8_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_7_process
      if (reset == 1'b1) begin
        x8_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x8_p <= x8;
        end
      end
    end



  assign x_shift9 = x8_p >>> 8'd8;



  assign y_temp9 = y8_p - x_shift9;



  assign y_temp_0_9_1 = y8_p + x_shift9;



  assign y9 = (switch_compare_1_18 == 1'b0 ? y_temp9 :
              y_temp_0_9_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_8_process
      if (reset == 1'b1) begin
        y9_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y9_p <= y9;
        end
      end
    end



  assign y9_p_msb = y9_p[33];



  assign switch_compare_1_20 = y9_p_msb > 1'b0;



  assign switch_compare_1_21 = y8_p_msb > 1'b0;



  assign y_shift9 = y8_p >>> 8'd8;



  assign x_temp9 = x8_p + y_shift9;



  assign x_temp_0_9_1 = x8_p - y_shift9;



  assign x9 = (switch_compare_1_21 == 1'b0 ? x_temp9 :
              x_temp_0_9_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_8_process
      if (reset == 1'b1) begin
        x9_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x9_p <= x9;
        end
      end
    end



  assign x_shift10 = x9_p >>> 8'd9;



  assign y_temp10 = y9_p - x_shift10;



  assign y_temp_0_10_1 = y9_p + x_shift10;



  assign y10 = (switch_compare_1_20 == 1'b0 ? y_temp10 :
              y_temp_0_10_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_9_process
      if (reset == 1'b1) begin
        y10_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y10_p <= y10;
        end
      end
    end



  assign y10_p_msb = y10_p[33];



  assign switch_compare_1_22 = y10_p_msb > 1'b0;



  assign switch_compare_1_23 = y9_p_msb > 1'b0;



  assign y_shift10 = y9_p >>> 8'd9;



  assign x_temp10 = x9_p + y_shift10;



  assign x_temp_0_10_1 = x9_p - y_shift10;



  assign x10 = (switch_compare_1_23 == 1'b0 ? x_temp10 :
              x_temp_0_10_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_9_process
      if (reset == 1'b1) begin
        x10_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x10_p <= x10;
        end
      end
    end



  assign x_shift11 = x10_p >>> 8'd10;



  assign y_temp11 = y10_p - x_shift11;



  assign y_temp_0_11_1 = y10_p + x_shift11;



  assign y11 = (switch_compare_1_22 == 1'b0 ? y_temp11 :
              y_temp_0_11_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_10_process
      if (reset == 1'b1) begin
        y11_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y11_p <= y11;
        end
      end
    end



  assign y11_p_msb = y11_p[33];



  assign switch_compare_1_24 = y11_p_msb > 1'b0;



  assign switch_compare_1_25 = y10_p_msb > 1'b0;



  assign y_shift11 = y10_p >>> 8'd10;



  assign x_temp11 = x10_p + y_shift11;



  assign x_temp_0_11_1 = x10_p - y_shift11;



  assign x11 = (switch_compare_1_25 == 1'b0 ? x_temp11 :
              x_temp_0_11_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_10_process
      if (reset == 1'b1) begin
        x11_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x11_p <= x11;
        end
      end
    end



  assign x_shift12 = x11_p >>> 8'd11;



  assign y_temp12 = y11_p - x_shift12;



  assign y_temp_0_12_1 = y11_p + x_shift12;



  assign y12 = (switch_compare_1_24 == 1'b0 ? y_temp12 :
              y_temp_0_12_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_11_process
      if (reset == 1'b1) begin
        y12_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y12_p <= y12;
        end
      end
    end



  assign y12_p_msb = y12_p[33];



  assign switch_compare_1_26 = y12_p_msb > 1'b0;



  assign switch_compare_1_27 = y11_p_msb > 1'b0;



  assign y_shift12 = y11_p >>> 8'd11;



  assign x_temp12 = x11_p + y_shift12;



  assign x_temp_0_12_1 = x11_p - y_shift12;



  assign x12 = (switch_compare_1_27 == 1'b0 ? x_temp12 :
              x_temp_0_12_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_11_process
      if (reset == 1'b1) begin
        x12_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x12_p <= x12;
        end
      end
    end



  assign x_shift13 = x12_p >>> 8'd12;



  assign y_temp13 = y12_p - x_shift13;



  assign y_temp_0_13_1 = y12_p + x_shift13;



  assign y13 = (switch_compare_1_26 == 1'b0 ? y_temp13 :
              y_temp_0_13_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_12_process
      if (reset == 1'b1) begin
        y13_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y13_p <= y13;
        end
      end
    end



  assign y13_p_msb = y13_p[33];



  assign switch_compare_1_28 = y13_p_msb > 1'b0;



  assign switch_compare_1_29 = y12_p_msb > 1'b0;



  assign y_shift13 = y12_p >>> 8'd12;



  assign x_temp13 = x12_p + y_shift13;



  assign x_temp_0_13_1 = x12_p - y_shift13;



  assign x13 = (switch_compare_1_29 == 1'b0 ? x_temp13 :
              x_temp_0_13_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_12_process
      if (reset == 1'b1) begin
        x13_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x13_p <= x13;
        end
      end
    end



  assign x_shift14 = x13_p >>> 8'd13;



  assign y_temp14 = y13_p - x_shift14;



  assign y_temp_0_14_1 = y13_p + x_shift14;



  assign y14 = (switch_compare_1_28 == 1'b0 ? y_temp14 :
              y_temp_0_14_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_13_process
      if (reset == 1'b1) begin
        y14_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y14_p <= y14;
        end
      end
    end



  assign y14_p_msb = y14_p[33];



  assign switch_compare_1_30 = y14_p_msb > 1'b0;



  assign switch_compare_1_31 = y13_p_msb > 1'b0;



  assign y_shift14 = y13_p >>> 8'd13;



  assign x_temp14 = x13_p + y_shift14;



  assign x_temp_0_14_1 = x13_p - y_shift14;



  assign x14 = (switch_compare_1_31 == 1'b0 ? x_temp14 :
              x_temp_0_14_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_13_process
      if (reset == 1'b1) begin
        x14_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x14_p <= x14;
        end
      end
    end



  assign x_shift15 = x14_p >>> 8'd14;



  assign y_temp15 = y14_p - x_shift15;



  assign y_temp_0_15_1 = y14_p + x_shift15;



  assign y15 = (switch_compare_1_30 == 1'b0 ? y_temp15 :
              y_temp_0_15_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_14_process
      if (reset == 1'b1) begin
        y15_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y15_p <= y15;
        end
      end
    end



  assign y15_p_msb = y15_p[33];



  assign switch_compare_1_32 = y15_p_msb > 1'b0;



  assign switch_compare_1_33 = y14_p_msb > 1'b0;



  assign y_shift15 = y14_p >>> 8'd14;



  assign x_temp15 = x14_p + y_shift15;



  assign x_temp_0_15_1 = x14_p - y_shift15;



  assign x15 = (switch_compare_1_33 == 1'b0 ? x_temp15 :
              x_temp_0_15_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_14_process
      if (reset == 1'b1) begin
        x15_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x15_p <= x15;
        end
      end
    end



  assign x_shift16 = x15_p >>> 8'd15;



  assign y_temp16 = y15_p - x_shift16;



  assign y_temp_0_16_1 = y15_p + x_shift16;



  assign y16 = (switch_compare_1_32 == 1'b0 ? y_temp16 :
              y_temp_0_16_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_15_process
      if (reset == 1'b1) begin
        y16_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y16_p <= y16;
        end
      end
    end



  assign y16_p_msb = y16_p[33];



  assign switch_compare_1_34 = y16_p_msb > 1'b0;



  assign switch_compare_1_35 = y15_p_msb > 1'b0;



  assign y_shift16 = y15_p >>> 8'd15;



  assign x_temp16 = x15_p + y_shift16;



  assign x_temp_0_16_1 = x15_p - y_shift16;



  assign x16 = (switch_compare_1_35 == 1'b0 ? x_temp16 :
              x_temp_0_16_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_15_process
      if (reset == 1'b1) begin
        x16_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x16_p <= x16;
        end
      end
    end



  assign x_shift17 = x16_p >>> 8'd16;



  assign y_temp17 = y16_p - x_shift17;



  assign y_temp_0_17_1 = y16_p + x_shift17;



  assign y17 = (switch_compare_1_34 == 1'b0 ? y_temp17 :
              y_temp_0_17_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_16_process
      if (reset == 1'b1) begin
        y17_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y17_p <= y17;
        end
      end
    end



  assign y17_p_msb = y17_p[33];



  assign switch_compare_1_36 = y17_p_msb > 1'b0;



  assign switch_compare_1_37 = y16_p_msb > 1'b0;



  assign y_shift17 = y16_p >>> 8'd16;



  assign x_temp17 = x16_p + y_shift17;



  assign x_temp_0_17_1 = x16_p - y_shift17;



  assign x17 = (switch_compare_1_37 == 1'b0 ? x_temp17 :
              x_temp_0_17_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_16_process
      if (reset == 1'b1) begin
        x17_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x17_p <= x17;
        end
      end
    end



  assign x_shift18 = x17_p >>> 8'd17;



  assign y_temp18 = y17_p - x_shift18;



  assign y_temp_0_18_1 = y17_p + x_shift18;



  assign y18 = (switch_compare_1_36 == 1'b0 ? y_temp18 :
              y_temp_0_18_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_17_process
      if (reset == 1'b1) begin
        y18_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y18_p <= y18;
        end
      end
    end



  assign y18_p_msb = y18_p[33];



  assign switch_compare_1_38 = y18_p_msb > 1'b0;



  assign switch_compare_1_39 = y17_p_msb > 1'b0;



  assign y_shift18 = y17_p >>> 8'd17;



  assign x_temp18 = x17_p + y_shift18;



  assign x_temp_0_18_1 = x17_p - y_shift18;



  assign x18 = (switch_compare_1_39 == 1'b0 ? x_temp18 :
              x_temp_0_18_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_17_process
      if (reset == 1'b1) begin
        x18_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x18_p <= x18;
        end
      end
    end



  assign x_shift19 = x18_p >>> 8'd18;



  assign y_temp19 = y18_p - x_shift19;



  assign y_temp_0_19_1 = y18_p + x_shift19;



  assign y19 = (switch_compare_1_38 == 1'b0 ? y_temp19 :
              y_temp_0_19_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_18_process
      if (reset == 1'b1) begin
        y19_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y19_p <= y19;
        end
      end
    end



  assign y19_p_msb = y19_p[33];



  assign switch_compare_1_40 = y19_p_msb > 1'b0;



  assign switch_compare_1_41 = y18_p_msb > 1'b0;



  assign y_shift19 = y18_p >>> 8'd18;



  assign x_temp19 = x18_p + y_shift19;



  assign x_temp_0_19_1 = x18_p - y_shift19;



  assign x19 = (switch_compare_1_41 == 1'b0 ? x_temp19 :
              x_temp_0_19_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_18_process
      if (reset == 1'b1) begin
        x19_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x19_p <= x19;
        end
      end
    end



  assign x_shift20 = x19_p >>> 8'd19;



  assign y_temp20 = y19_p - x_shift20;



  assign y_temp_0_20_1 = y19_p + x_shift20;



  assign y20 = (switch_compare_1_40 == 1'b0 ? y_temp20 :
              y_temp_0_20_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_19_process
      if (reset == 1'b1) begin
        y20_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y20_p <= y20;
        end
      end
    end



  assign y20_p_msb = y20_p[33];



  assign switch_compare_1_42 = y20_p_msb > 1'b0;



  assign switch_compare_1_43 = y19_p_msb > 1'b0;



  assign y_shift20 = y19_p >>> 8'd19;



  assign x_temp20 = x19_p + y_shift20;



  assign x_temp_0_20_1 = x19_p - y_shift20;



  assign x20 = (switch_compare_1_43 == 1'b0 ? x_temp20 :
              x_temp_0_20_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_19_process
      if (reset == 1'b1) begin
        x20_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x20_p <= x20;
        end
      end
    end



  assign x_shift21 = x20_p >>> 8'd20;



  assign y_temp21 = y20_p - x_shift21;



  assign y_temp_0_21_1 = y20_p + x_shift21;



  assign y21 = (switch_compare_1_42 == 1'b0 ? y_temp21 :
              y_temp_0_21_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_20_process
      if (reset == 1'b1) begin
        y21_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y21_p <= y21;
        end
      end
    end



  assign y21_p_msb = y21_p[33];



  assign switch_compare_1_44 = y21_p_msb > 1'b0;



  assign switch_compare_1_45 = y20_p_msb > 1'b0;



  assign y_shift21 = y20_p >>> 8'd20;



  assign x_temp21 = x20_p + y_shift21;



  assign x_temp_0_21_1 = x20_p - y_shift21;



  assign x21 = (switch_compare_1_45 == 1'b0 ? x_temp21 :
              x_temp_0_21_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_20_process
      if (reset == 1'b1) begin
        x21_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x21_p <= x21;
        end
      end
    end



  assign x_shift22 = x21_p >>> 8'd21;



  assign y_temp22 = y21_p - x_shift22;



  assign y_temp_0_22_1 = y21_p + x_shift22;



  assign y22 = (switch_compare_1_44 == 1'b0 ? y_temp22 :
              y_temp_0_22_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_21_process
      if (reset == 1'b1) begin
        y22_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y22_p <= y22;
        end
      end
    end



  assign y22_p_msb = y22_p[33];



  assign switch_compare_1_46 = y22_p_msb > 1'b0;



  assign switch_compare_1_47 = y21_p_msb > 1'b0;



  assign y_shift22 = y21_p >>> 8'd21;



  assign x_temp22 = x21_p + y_shift22;



  assign x_temp_0_22_1 = x21_p - y_shift22;



  assign x22 = (switch_compare_1_47 == 1'b0 ? x_temp22 :
              x_temp_0_22_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_21_process
      if (reset == 1'b1) begin
        x22_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x22_p <= x22;
        end
      end
    end



  assign x_shift23 = x22_p >>> 8'd22;



  assign y_temp23 = y22_p - x_shift23;



  assign y_temp_0_23_1 = y22_p + x_shift23;



  assign y23 = (switch_compare_1_46 == 1'b0 ? y_temp23 :
              y_temp_0_23_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_22_process
      if (reset == 1'b1) begin
        y23_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y23_p <= y23;
        end
      end
    end



  assign y23_p_msb = y23_p[33];



  assign switch_compare_1_48 = y23_p_msb > 1'b0;



  assign switch_compare_1_49 = y22_p_msb > 1'b0;



  assign y_shift23 = y22_p >>> 8'd22;



  assign x_temp23 = x22_p + y_shift23;



  assign x_temp_0_23_1 = x22_p - y_shift23;



  assign x23 = (switch_compare_1_49 == 1'b0 ? x_temp23 :
              x_temp_0_23_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_22_process
      if (reset == 1'b1) begin
        x23_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x23_p <= x23;
        end
      end
    end



  assign x_shift24 = x23_p >>> 8'd23;



  assign y_temp24 = y23_p - x_shift24;



  assign y_temp_0_24_1 = y23_p + x_shift24;



  assign y24 = (switch_compare_1_48 == 1'b0 ? y_temp24 :
              y_temp_0_24_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_23_process
      if (reset == 1'b1) begin
        y24_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y24_p <= y24;
        end
      end
    end



  assign y24_p_msb = y24_p[33];



  assign switch_compare_1_50 = y24_p_msb > 1'b0;



  assign switch_compare_1_51 = y23_p_msb > 1'b0;



  assign y_shift24 = y23_p >>> 8'd23;



  assign x_temp24 = x23_p + y_shift24;



  assign x_temp_0_24_1 = x23_p - y_shift24;



  assign x24 = (switch_compare_1_51 == 1'b0 ? x_temp24 :
              x_temp_0_24_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_23_process
      if (reset == 1'b1) begin
        x24_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x24_p <= x24;
        end
      end
    end



  assign x_shift25 = x24_p >>> 8'd24;



  assign y_temp25 = y24_p - x_shift25;



  assign y_temp_0_25_1 = y24_p + x_shift25;



  assign y25 = (switch_compare_1_50 == 1'b0 ? y_temp25 :
              y_temp_0_25_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_24_process
      if (reset == 1'b1) begin
        y25_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y25_p <= y25;
        end
      end
    end



  assign y25_p_msb = y25_p[33];



  assign switch_compare_1_52 = y25_p_msb > 1'b0;



  assign switch_compare_1_53 = y24_p_msb > 1'b0;



  assign y_shift25 = y24_p >>> 8'd24;



  assign x_temp25 = x24_p + y_shift25;



  assign x_temp_0_25_1 = x24_p - y_shift25;



  assign x25 = (switch_compare_1_53 == 1'b0 ? x_temp25 :
              x_temp_0_25_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_24_process
      if (reset == 1'b1) begin
        x25_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x25_p <= x25;
        end
      end
    end



  assign x_shift26 = x25_p >>> 8'd25;



  assign y_temp26 = y25_p - x_shift26;



  assign y_temp_0_26_1 = y25_p + x_shift26;



  assign y26 = (switch_compare_1_52 == 1'b0 ? y_temp26 :
              y_temp_0_26_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_25_process
      if (reset == 1'b1) begin
        y26_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y26_p <= y26;
        end
      end
    end



  assign y26_p_msb = y26_p[33];



  assign switch_compare_1_54 = y26_p_msb > 1'b0;



  assign switch_compare_1_55 = y25_p_msb > 1'b0;



  assign y_shift26 = y25_p >>> 8'd25;



  assign x_temp26 = x25_p + y_shift26;



  assign x_temp_0_26_1 = x25_p - y_shift26;



  assign x26 = (switch_compare_1_55 == 1'b0 ? x_temp26 :
              x_temp_0_26_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_25_process
      if (reset == 1'b1) begin
        x26_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x26_p <= x26;
        end
      end
    end



  assign x_shift27 = x26_p >>> 8'd26;



  assign y_temp27 = y26_p - x_shift27;



  assign y_temp_0_27_1 = y26_p + x_shift27;



  assign y27 = (switch_compare_1_54 == 1'b0 ? y_temp27 :
              y_temp_0_27_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_26_process
      if (reset == 1'b1) begin
        y27_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y27_p <= y27;
        end
      end
    end



  assign y27_p_msb = y27_p[33];



  assign switch_compare_1_56 = y27_p_msb > 1'b0;



  assign switch_compare_1_57 = y26_p_msb > 1'b0;



  assign y_shift27 = y26_p >>> 8'd26;



  assign x_temp27 = x26_p + y_shift27;



  assign x_temp_0_27_1 = x26_p - y_shift27;



  assign x27 = (switch_compare_1_57 == 1'b0 ? x_temp27 :
              x_temp_0_27_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_26_process
      if (reset == 1'b1) begin
        x27_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x27_p <= x27;
        end
      end
    end



  assign x_shift28 = x27_p >>> 8'd27;



  assign y_temp28 = y27_p - x_shift28;



  assign y_temp_0_28_1 = y27_p + x_shift28;



  assign y28 = (switch_compare_1_56 == 1'b0 ? y_temp28 :
              y_temp_0_28_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_27_process
      if (reset == 1'b1) begin
        y28_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y28_p <= y28;
        end
      end
    end



  assign y28_p_msb = y28_p[33];



  assign switch_compare_1_58 = y28_p_msb > 1'b0;



  assign switch_compare_1_59 = y27_p_msb > 1'b0;



  assign y_shift28 = y27_p >>> 8'd27;



  assign x_temp28 = x27_p + y_shift28;



  assign x_temp_0_28_1 = x27_p - y_shift28;



  assign x28 = (switch_compare_1_59 == 1'b0 ? x_temp28 :
              x_temp_0_28_1);



  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_27_process
      if (reset == 1'b1) begin
        x28_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          x28_p <= x28;
        end
      end
    end



  assign x_shift29 = x28_p >>> 8'd28;



  assign y_temp29 = y28_p - x_shift29;



  assign y_temp_0_29_1 = y28_p + x_shift29;



  assign y29 = (switch_compare_1_58 == 1'b0 ? y_temp29 :
              y_temp_0_29_1);



  always @(posedge clk or posedge reset)
    begin : y_reg_28_process
      if (reset == 1'b1) begin
        y29_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          y29_p <= y29;
        end
      end
    end



  assign y29_p_msb = y29_p[33];



  assign switch_compare_1_60 = y29_p_msb > 1'b0;



  assign switch_compare_1_61 = y28_p_msb > 1'b0;



  assign switch_compare_1_62 = y27_p_msb > 1'b0;



  assign switch_compare_1_63 = y26_p_msb > 1'b0;



  assign switch_compare_1_64 = y25_p_msb > 1'b0;



  assign switch_compare_1_65 = y24_p_msb > 1'b0;



  assign switch_compare_1_66 = y23_p_msb > 1'b0;



  assign switch_compare_1_67 = y22_p_msb > 1'b0;



  assign switch_compare_1_68 = y21_p_msb > 1'b0;



  assign switch_compare_1_69 = y20_p_msb > 1'b0;



  assign switch_compare_1_70 = y19_p_msb > 1'b0;



  assign switch_compare_1_71 = y18_p_msb > 1'b0;



  assign switch_compare_1_72 = y17_p_msb > 1'b0;



  assign switch_compare_1_73 = y16_p_msb > 1'b0;



  assign switch_compare_1_74 = y15_p_msb > 1'b0;



  assign switch_compare_1_75 = y14_p_msb > 1'b0;



  assign switch_compare_1_76 = y13_p_msb > 1'b0;



  assign switch_compare_1_77 = y12_p_msb > 1'b0;



  assign switch_compare_1_78 = y11_p_msb > 1'b0;



  assign switch_compare_1_79 = y10_p_msb > 1'b0;



  assign switch_compare_1_80 = y9_p_msb > 1'b0;



  assign switch_compare_1_81 = y8_p_msb > 1'b0;



  assign switch_compare_1_82 = y7_p_msb > 1'b0;



  assign switch_compare_1_83 = y6_p_msb > 1'b0;



  assign switch_compare_1_84 = y5_p_msb > 1'b0;



  assign switch_compare_1_85 = y4_p_msb > 1'b0;



  assign switch_compare_1_86 = y3_p_msb > 1'b0;



  assign switch_compare_1_87 = y2_p_msb > 1'b0;



  assign switch_compare_1_88 = y1_p_msb > 1'b0;



  assign switch_compare_1_89 = y0_p_msb > 1'b0;



  assign z0 = 34'sh000000000;



  assign lut_value_s1 = 34'sh01921FB54;



  assign lut_value_temp1 = z0 + lut_value_s1;



  assign y_temp_0_1_2 = z0 - lut_value_s1;



  assign z1 = (switch_compare_1_89 == 1'b0 ? lut_value_temp1 :
              y_temp_0_1_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_process
      if (reset == 1'b1) begin
        z1_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z1_p <= z1;
        end
      end
    end



  assign lut_value_s2 = 34'sh00ED63383;



  assign lut_value_temp2 = z1_p + lut_value_s2;



  assign y_temp_0_2_2 = z1_p - lut_value_s2;



  assign z2 = (switch_compare_1_88 == 1'b0 ? lut_value_temp2 :
              y_temp_0_2_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_1_process
      if (reset == 1'b1) begin
        z2_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z2_p <= z2;
        end
      end
    end



  assign lut_value_s3 = 34'sh007D6DD7E;



  assign lut_value_temp3 = z2_p + lut_value_s3;



  assign y_temp_0_3_2 = z2_p - lut_value_s3;



  assign z3 = (switch_compare_1_87 == 1'b0 ? lut_value_temp3 :
              y_temp_0_3_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_2_process
      if (reset == 1'b1) begin
        z3_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z3_p <= z3;
        end
      end
    end



  assign lut_value_s4 = 34'sh003FAB753;



  assign lut_value_temp4 = z3_p + lut_value_s4;



  assign y_temp_0_4_2 = z3_p - lut_value_s4;



  assign z4 = (switch_compare_1_86 == 1'b0 ? lut_value_temp4 :
              y_temp_0_4_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_3_process
      if (reset == 1'b1) begin
        z4_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z4_p <= z4;
        end
      end
    end



  assign lut_value_s5 = 34'sh001FF55BB;



  assign lut_value_temp5 = z4_p + lut_value_s5;



  assign y_temp_0_5_2 = z4_p - lut_value_s5;



  assign z5 = (switch_compare_1_85 == 1'b0 ? lut_value_temp5 :
              y_temp_0_5_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_4_process
      if (reset == 1'b1) begin
        z5_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z5_p <= z5;
        end
      end
    end



  assign lut_value_s6 = 34'sh000FFEAAE;



  assign lut_value_temp6 = z5_p + lut_value_s6;



  assign y_temp_0_6_2 = z5_p - lut_value_s6;



  assign z6 = (switch_compare_1_84 == 1'b0 ? lut_value_temp6 :
              y_temp_0_6_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_5_process
      if (reset == 1'b1) begin
        z6_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z6_p <= z6;
        end
      end
    end



  assign lut_value_s7 = 34'sh0007FFD55;



  assign lut_value_temp7 = z6_p + lut_value_s7;



  assign y_temp_0_7_2 = z6_p - lut_value_s7;



  assign z7 = (switch_compare_1_83 == 1'b0 ? lut_value_temp7 :
              y_temp_0_7_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_6_process
      if (reset == 1'b1) begin
        z7_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z7_p <= z7;
        end
      end
    end



  assign lut_value_s8 = 34'sh0003FFFAB;



  assign lut_value_temp8 = z7_p + lut_value_s8;



  assign y_temp_0_8_2 = z7_p - lut_value_s8;



  assign z8 = (switch_compare_1_82 == 1'b0 ? lut_value_temp8 :
              y_temp_0_8_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_7_process
      if (reset == 1'b1) begin
        z8_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z8_p <= z8;
        end
      end
    end



  assign lut_value_s9 = 34'sh0001FFFF5;



  assign lut_value_temp9 = z8_p + lut_value_s9;



  assign y_temp_0_9_2 = z8_p - lut_value_s9;



  assign z9 = (switch_compare_1_81 == 1'b0 ? lut_value_temp9 :
              y_temp_0_9_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_8_process
      if (reset == 1'b1) begin
        z9_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z9_p <= z9;
        end
      end
    end



  assign lut_value_s10 = 34'sh0000FFFFF;



  assign lut_value_temp10 = z9_p + lut_value_s10;



  assign y_temp_0_10_2 = z9_p - lut_value_s10;



  assign z10 = (switch_compare_1_80 == 1'b0 ? lut_value_temp10 :
              y_temp_0_10_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_9_process
      if (reset == 1'b1) begin
        z10_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z10_p <= z10;
        end
      end
    end



  assign lut_value_s11 = 34'sh000080000;



  assign lut_value_temp11 = z10_p + lut_value_s11;



  assign y_temp_0_11_2 = z10_p - lut_value_s11;



  assign z11 = (switch_compare_1_79 == 1'b0 ? lut_value_temp11 :
              y_temp_0_11_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_10_process
      if (reset == 1'b1) begin
        z11_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z11_p <= z11;
        end
      end
    end



  assign lut_value_s12 = 34'sh000040000;



  assign lut_value_temp12 = z11_p + lut_value_s12;



  assign y_temp_0_12_2 = z11_p - lut_value_s12;



  assign z12 = (switch_compare_1_78 == 1'b0 ? lut_value_temp12 :
              y_temp_0_12_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_11_process
      if (reset == 1'b1) begin
        z12_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z12_p <= z12;
        end
      end
    end



  assign lut_value_s13 = 34'sh000020000;



  assign lut_value_temp13 = z12_p + lut_value_s13;



  assign y_temp_0_13_2 = z12_p - lut_value_s13;



  assign z13 = (switch_compare_1_77 == 1'b0 ? lut_value_temp13 :
              y_temp_0_13_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_12_process
      if (reset == 1'b1) begin
        z13_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z13_p <= z13;
        end
      end
    end



  assign lut_value_s14 = 34'sh000010000;



  assign lut_value_temp14 = z13_p + lut_value_s14;



  assign y_temp_0_14_2 = z13_p - lut_value_s14;



  assign z14 = (switch_compare_1_76 == 1'b0 ? lut_value_temp14 :
              y_temp_0_14_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_13_process
      if (reset == 1'b1) begin
        z14_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z14_p <= z14;
        end
      end
    end



  assign lut_value_s15 = 34'sh000008000;



  assign lut_value_temp15 = z14_p + lut_value_s15;



  assign y_temp_0_15_2 = z14_p - lut_value_s15;



  assign z15 = (switch_compare_1_75 == 1'b0 ? lut_value_temp15 :
              y_temp_0_15_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_14_process
      if (reset == 1'b1) begin
        z15_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z15_p <= z15;
        end
      end
    end



  assign lut_value_s16 = 34'sh000004000;



  assign lut_value_temp16 = z15_p + lut_value_s16;



  assign y_temp_0_16_2 = z15_p - lut_value_s16;



  assign z16 = (switch_compare_1_74 == 1'b0 ? lut_value_temp16 :
              y_temp_0_16_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_15_process
      if (reset == 1'b1) begin
        z16_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z16_p <= z16;
        end
      end
    end



  assign lut_value_s17 = 34'sh000002000;



  assign lut_value_temp17 = z16_p + lut_value_s17;



  assign y_temp_0_17_2 = z16_p - lut_value_s17;



  assign z17 = (switch_compare_1_73 == 1'b0 ? lut_value_temp17 :
              y_temp_0_17_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_16_process
      if (reset == 1'b1) begin
        z17_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z17_p <= z17;
        end
      end
    end



  assign lut_value_s18 = 34'sh000001000;



  assign lut_value_temp18 = z17_p + lut_value_s18;



  assign y_temp_0_18_2 = z17_p - lut_value_s18;



  assign z18 = (switch_compare_1_72 == 1'b0 ? lut_value_temp18 :
              y_temp_0_18_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_17_process
      if (reset == 1'b1) begin
        z18_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z18_p <= z18;
        end
      end
    end



  assign lut_value_s19 = 34'sh000000800;



  assign lut_value_temp19 = z18_p + lut_value_s19;



  assign y_temp_0_19_2 = z18_p - lut_value_s19;



  assign z19 = (switch_compare_1_71 == 1'b0 ? lut_value_temp19 :
              y_temp_0_19_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_18_process
      if (reset == 1'b1) begin
        z19_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z19_p <= z19;
        end
      end
    end



  assign lut_value_s20 = 34'sh000000400;



  assign lut_value_temp20 = z19_p + lut_value_s20;



  assign y_temp_0_20_2 = z19_p - lut_value_s20;



  assign z20 = (switch_compare_1_70 == 1'b0 ? lut_value_temp20 :
              y_temp_0_20_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_19_process
      if (reset == 1'b1) begin
        z20_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z20_p <= z20;
        end
      end
    end



  assign lut_value_s21 = 34'sh000000200;



  assign lut_value_temp21 = z20_p + lut_value_s21;



  assign y_temp_0_21_2 = z20_p - lut_value_s21;



  assign z21 = (switch_compare_1_69 == 1'b0 ? lut_value_temp21 :
              y_temp_0_21_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_20_process
      if (reset == 1'b1) begin
        z21_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z21_p <= z21;
        end
      end
    end



  assign lut_value_s22 = 34'sh000000100;



  assign lut_value_temp22 = z21_p + lut_value_s22;



  assign y_temp_0_22_2 = z21_p - lut_value_s22;



  assign z22 = (switch_compare_1_68 == 1'b0 ? lut_value_temp22 :
              y_temp_0_22_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_21_process
      if (reset == 1'b1) begin
        z22_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z22_p <= z22;
        end
      end
    end



  assign lut_value_s23 = 34'sh000000080;



  assign lut_value_temp23 = z22_p + lut_value_s23;



  assign y_temp_0_23_2 = z22_p - lut_value_s23;



  assign z23 = (switch_compare_1_67 == 1'b0 ? lut_value_temp23 :
              y_temp_0_23_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_22_process
      if (reset == 1'b1) begin
        z23_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z23_p <= z23;
        end
      end
    end



  assign lut_value_s24 = 34'sh000000040;



  assign lut_value_temp24 = z23_p + lut_value_s24;



  assign y_temp_0_24_2 = z23_p - lut_value_s24;



  assign z24 = (switch_compare_1_66 == 1'b0 ? lut_value_temp24 :
              y_temp_0_24_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_23_process
      if (reset == 1'b1) begin
        z24_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z24_p <= z24;
        end
      end
    end



  assign lut_value_s25 = 34'sh000000020;



  assign lut_value_temp25 = z24_p + lut_value_s25;



  assign y_temp_0_25_2 = z24_p - lut_value_s25;



  assign z25 = (switch_compare_1_65 == 1'b0 ? lut_value_temp25 :
              y_temp_0_25_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_24_process
      if (reset == 1'b1) begin
        z25_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z25_p <= z25;
        end
      end
    end



  assign lut_value_s26 = 34'sh000000010;



  assign lut_value_temp26 = z25_p + lut_value_s26;



  assign y_temp_0_26_2 = z25_p - lut_value_s26;



  assign z26 = (switch_compare_1_64 == 1'b0 ? lut_value_temp26 :
              y_temp_0_26_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_25_process
      if (reset == 1'b1) begin
        z26_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z26_p <= z26;
        end
      end
    end



  assign lut_value_s27 = 34'sh000000008;



  assign lut_value_temp27 = z26_p + lut_value_s27;



  assign y_temp_0_27_2 = z26_p - lut_value_s27;



  assign z27 = (switch_compare_1_63 == 1'b0 ? lut_value_temp27 :
              y_temp_0_27_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_26_process
      if (reset == 1'b1) begin
        z27_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z27_p <= z27;
        end
      end
    end



  assign lut_value_s28 = 34'sh000000004;



  assign lut_value_temp28 = z27_p + lut_value_s28;



  assign y_temp_0_28_2 = z27_p - lut_value_s28;



  assign z28 = (switch_compare_1_62 == 1'b0 ? lut_value_temp28 :
              y_temp_0_28_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_27_process
      if (reset == 1'b1) begin
        z28_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z28_p <= z28;
        end
      end
    end



  assign lut_value_s29 = 34'sh000000002;



  assign lut_value_temp29 = z28_p + lut_value_s29;



  assign y_temp_0_29_2 = z28_p - lut_value_s29;



  assign z29 = (switch_compare_1_61 == 1'b0 ? lut_value_temp29 :
              y_temp_0_29_2);



  always @(posedge clk or posedge reset)
    begin : z_reg_28_process
      if (reset == 1'b1) begin
        z29_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z29_p <= z29;
        end
      end
    end



  assign lut_value_s30 = 34'sh000000001;



  assign lut_value_temp30 = z29_p + lut_value_s30;



  assign y_temp_0_30 = z29_p - lut_value_s30;



  assign z30 = (switch_compare_1_60 == 1'b0 ? lut_value_temp30 :
              y_temp_0_30);



  always @(posedge clk or posedge reset)
    begin : z_reg_29_process
      if (reset == 1'b1) begin
        z30_p <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          z30_p <= z30;
        end
      end
    end



  assign z_out = z30_p[31:0];



  assign z_temp3_cast = {z_out[31], z_out};
  assign z_temp3_cast_1 =  - (z_temp3_cast);
  assign z_temp3_1 = z_temp3_cast_1[31:0];



  assign z_temp2_1 = onePi_1 - z_out;



  assign z_temp1_1 = z_out - onePi_1;



  always @(onePi_1, x_y_adjust, z_out, z_temp1_1, z_temp2_1, z_temp3_1, zero) begin
    case ( x_y_adjust)
      3'b000 :
        begin
          z_out_adjust = zero;
        end
      3'b001 :
        begin
          z_out_adjust = zero;
        end
      3'b010 :
        begin
          z_out_adjust = onePi_1;
        end
      3'b011 :
        begin
          z_out_adjust = onePi_1;
        end
      3'b100 :
        begin
          z_out_adjust = z_out;
        end
      3'b101 :
        begin
          z_out_adjust = z_temp3_1;
        end
      3'b110 :
        begin
          z_out_adjust = z_temp2_1;
        end
      default :
        begin
          z_out_adjust = z_temp1_1;
        end
    endcase
  end



  // Pipeline register for output z
  always @(posedge clk or posedge reset)
    begin : z_out_reg_process
      if (reset == 1'b1) begin
        angle_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          angle_1 <= z_out_adjust;
        end
      end
    end



  assign angle = angle_1;

endmodule  // atan2_cordic_nw

