// -------------------------------------------------------------
// 
// File Name: F:\apparatlab2\fixed\calk\Sqrt.v
// Created: 2023-01-16 23:59:55
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sqrt
// Source Path: calk/CALC_MAGNITUDE_AND_PHASE_FIXED/Sqrt
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sqrt
          (clk,
           reset,
           enb,
           din,
           dout);


  input   clk;
  input   reset;
  input   enb;
  input   [64:0] din;  // ufix65_En55
  output  signed [32:0] dout;  // sfix33_En18


  wire [9:0] Root_Square4_temp1;  // ufix10
  wire [65:0] resizedin;  // ufix66_En36
  wire [65:0] resizedin_temp;  // ufix66
  wire [9:0] din_temp_0;  // ufix10
  wire relop_relop1;
  wire [4:0] root_0_temp0;  // ufix5
  wire [4:0] root_0_temp1;  // ufix5
  wire [4:0] Root_0;  // ufix5
  reg [4:0] currentRoot1_p;  // ufix5
  wire [9:0] Root_Square4_temp0;  // ufix10
  wire [9:0] Root_Square0;  // ufix10
  reg [9:0] currentRoot_Square1_p;  // ufix10
  wire [1:0] constant_01;  // ufix2
  wire [11:0] prevRoot_Square_extend1;  // ufix12
  wire [1:0] constant_01_1;  // ufix2
  wire [6:0] prevRoot_extend1;  // ufix7
  wire [12:0] adder_add_temp;  // ufix13
  wire [12:0] adder_1;  // ufix13
  wire [12:0] adder_2;  // ufix13
  wire [11:0] Root_Square5_temp1;  // ufix12
  reg [65:0] resizedin1_p;  // ufix66
  wire [11:0] din_temp_1;  // ufix12
  wire relop_relop1_1;
  wire [5:0] Root_1;  // ufix6
  reg [5:0] currentRoot2_p;  // ufix6
  wire [11:0] Root_Square5_temp0;  // ufix12
  wire [11:0] Root_Square1;  // ufix12
  reg [11:0] currentRoot_Square2_p;  // ufix12
  wire [1:0] constant_02;  // ufix2
  wire [13:0] prevRoot_Square_extend2;  // ufix14
  wire [1:0] constant_02_1;  // ufix2
  wire [7:0] prevRoot_extend2;  // ufix8
  wire [14:0] adder_add_temp_1;  // ufix15
  wire [14:0] adder_4;  // ufix15
  wire [14:0] adder_5;  // ufix15
  wire [13:0] Root_Square6_temp1;  // ufix14
  reg [65:0] resizedin2_p;  // ufix66
  wire [13:0] din_temp_2;  // ufix14
  wire relop_relop1_2;
  wire [6:0] Root_2;  // ufix7
  reg [6:0] currentRoot3_p;  // ufix7
  wire [13:0] Root_Square6_temp0;  // ufix14
  wire [13:0] Root_Square2;  // ufix14
  reg [13:0] currentRoot_Square3_p;  // ufix14
  wire [1:0] constant_03;  // ufix2
  wire [15:0] prevRoot_Square_extend3;  // ufix16
  wire [1:0] constant_03_1;  // ufix2
  wire [8:0] prevRoot_extend3;  // ufix9
  wire [16:0] adder_add_temp_2;  // ufix17
  wire [16:0] adder_7;  // ufix17
  wire [16:0] adder_8;  // ufix17
  wire [15:0] Root_Square7_temp1;  // ufix16
  reg [65:0] resizedin3_p;  // ufix66
  wire [15:0] din_temp_3;  // ufix16
  wire relop_relop1_3;
  wire [7:0] Root_3;  // ufix8
  reg [7:0] currentRoot4_p;  // ufix8
  wire [15:0] Root_Square7_temp0;  // ufix16
  wire [15:0] Root_Square3;  // ufix16
  reg [15:0] currentRoot_Square4_p;  // ufix16
  wire [1:0] constant_04;  // ufix2
  wire [17:0] prevRoot_Square_extend4;  // ufix18
  wire [1:0] constant_04_1;  // ufix2
  wire [9:0] prevRoot_extend4;  // ufix10
  wire [18:0] adder_add_temp_3;  // ufix19
  wire [18:0] adder_10;  // ufix19
  wire [18:0] adder_11;  // ufix19
  wire [17:0] Root_Square8_temp1;  // ufix18
  reg [65:0] resizedin4_p;  // ufix66
  wire [17:0] din_temp_4;  // ufix18
  wire relop_relop1_4;
  wire [8:0] Root_4;  // ufix9
  reg [8:0] currentRoot5_p;  // ufix9
  wire [17:0] Root_Square8_temp0;  // ufix18
  wire [17:0] Root_Square4;  // ufix18
  reg [17:0] currentRoot_Square5_p;  // ufix18
  wire [1:0] constant_05;  // ufix2
  wire [19:0] prevRoot_Square_extend5;  // ufix20
  wire [1:0] constant_05_1;  // ufix2
  wire [10:0] prevRoot_extend5;  // ufix11
  wire [20:0] adder_add_temp_4;  // ufix21
  wire [20:0] adder_13;  // ufix21
  wire [20:0] adder_14;  // ufix21
  wire [19:0] Root_Square9_temp1;  // ufix20
  reg [65:0] resizedin5_p;  // ufix66
  wire [19:0] din_temp_5;  // ufix20
  wire relop_relop1_5;
  wire [9:0] Root_5;  // ufix10
  reg [9:0] currentRoot6_p;  // ufix10
  wire [19:0] Root_Square9_temp0;  // ufix20
  wire [19:0] Root_Square5;  // ufix20
  reg [19:0] currentRoot_Square6_p;  // ufix20
  wire [1:0] constant_06;  // ufix2
  wire [21:0] prevRoot_Square_extend6;  // ufix22
  wire [1:0] constant_06_1;  // ufix2
  wire [11:0] prevRoot_extend6;  // ufix12
  wire [22:0] adder_add_temp_5;  // ufix23
  wire [22:0] adder_16;  // ufix23
  wire [22:0] adder_17;  // ufix23
  wire [21:0] Root_Square10_temp1;  // ufix22
  reg [65:0] resizedin6_p;  // ufix66
  wire [21:0] din_temp_6;  // ufix22
  wire relop_relop1_6;
  wire [10:0] Root_6;  // ufix11
  reg [10:0] currentRoot7_p;  // ufix11
  wire [21:0] Root_Square10_temp0;  // ufix22
  wire [21:0] Root_Square6;  // ufix22
  reg [21:0] currentRoot_Square7_p;  // ufix22
  wire [1:0] constant_07;  // ufix2
  wire [23:0] prevRoot_Square_extend7;  // ufix24
  wire [1:0] constant_07_1;  // ufix2
  wire [12:0] prevRoot_extend7;  // ufix13
  wire [24:0] adder_add_temp_6;  // ufix25
  wire [24:0] adder_19;  // ufix25
  wire [24:0] adder_20;  // ufix25
  wire [23:0] Root_Square11_temp1;  // ufix24
  reg [65:0] resizedin7_p;  // ufix66
  wire [23:0] din_temp_7;  // ufix24
  wire relop_relop1_7;
  wire [11:0] Root_7;  // ufix12
  reg [11:0] currentRoot8_p;  // ufix12
  wire [23:0] Root_Square11_temp0;  // ufix24
  wire [23:0] Root_Square7;  // ufix24
  reg [23:0] currentRoot_Square8_p;  // ufix24
  wire [1:0] constant_08;  // ufix2
  wire [25:0] prevRoot_Square_extend8;  // ufix26
  wire [1:0] constant_08_1;  // ufix2
  wire [13:0] prevRoot_extend8;  // ufix14
  wire [26:0] adder_add_temp_7;  // ufix27
  wire [26:0] adder_22;  // ufix27
  wire [26:0] adder_23;  // ufix27
  wire [25:0] Root_Square12_temp1;  // ufix26
  reg [65:0] resizedin8_p;  // ufix66
  wire [25:0] din_temp_8;  // ufix26
  wire relop_relop1_8;
  wire [12:0] Root_8;  // ufix13
  reg [12:0] currentRoot9_p;  // ufix13
  wire [25:0] Root_Square12_temp0;  // ufix26
  wire [25:0] Root_Square8;  // ufix26
  reg [25:0] currentRoot_Square9_p;  // ufix26
  wire [1:0] constant_09;  // ufix2
  wire [27:0] prevRoot_Square_extend9;  // ufix28
  wire [1:0] constant_09_1;  // ufix2
  wire [14:0] prevRoot_extend9;  // ufix15
  wire [28:0] adder_add_temp_8;  // ufix29
  wire [28:0] adder_25;  // ufix29
  wire [28:0] adder_26;  // ufix29
  wire [27:0] Root_Square13_temp1;  // ufix28
  reg [65:0] resizedin9_p;  // ufix66
  wire [27:0] din_temp_9;  // ufix28
  wire relop_relop1_9;
  wire [13:0] Root_9;  // ufix14
  reg [13:0] currentRoot10_p;  // ufix14
  wire [27:0] Root_Square13_temp0;  // ufix28
  wire [27:0] Root_Square9;  // ufix28
  reg [27:0] currentRoot_Square10_p;  // ufix28
  wire [1:0] constant_010;  // ufix2
  wire [29:0] prevRoot_Square_extend10;  // ufix30
  wire [1:0] constant_010_1;  // ufix2
  wire [15:0] prevRoot_extend10;  // ufix16
  wire [30:0] adder_add_temp_9;  // ufix31
  wire [30:0] adder_28;  // ufix31
  wire [30:0] adder_29;  // ufix31
  wire [29:0] Root_Square14_temp1;  // ufix30
  reg [65:0] resizedin10_p;  // ufix66
  wire [29:0] din_temp_10;  // ufix30
  wire relop_relop1_10;
  wire [14:0] Root_10;  // ufix15
  reg [14:0] currentRoot11_p;  // ufix15
  wire [29:0] Root_Square14_temp0;  // ufix30
  wire [29:0] Root_Square10;  // ufix30
  reg [29:0] currentRoot_Square11_p;  // ufix30
  wire [1:0] constant_011;  // ufix2
  wire [31:0] prevRoot_Square_extend11;  // ufix32
  wire [1:0] constant_011_1;  // ufix2
  wire [16:0] prevRoot_extend11;  // ufix17
  wire [32:0] adder_add_temp_10;  // ufix33
  wire [32:0] adder_31;  // ufix33
  wire [32:0] adder_32;  // ufix33
  wire [31:0] Root_Square15_temp1;  // ufix32
  reg [65:0] resizedin11_p;  // ufix66
  wire [31:0] din_temp_11;  // ufix32
  wire relop_relop1_11;
  wire [15:0] Root_11;  // ufix16
  reg [15:0] currentRoot12_p;  // ufix16
  wire [31:0] Root_Square15_temp0;  // ufix32
  wire [31:0] Root_Square11;  // ufix32
  reg [31:0] currentRoot_Square12_p;  // ufix32
  wire [1:0] constant_012;  // ufix2
  wire [33:0] prevRoot_Square_extend12;  // ufix34
  wire [1:0] constant_012_1;  // ufix2
  wire [17:0] prevRoot_extend12;  // ufix18
  wire [34:0] adder_add_temp_11;  // ufix35
  wire [34:0] adder_34;  // ufix35
  wire [34:0] adder_35;  // ufix35
  wire [33:0] Root_Square16_temp1;  // ufix34
  reg [65:0] resizedin12_p;  // ufix66
  wire [33:0] din_temp_12;  // ufix34
  wire relop_relop1_12;
  wire [16:0] Root_12;  // ufix17
  reg [16:0] currentRoot13_p;  // ufix17
  wire [33:0] Root_Square16_temp0;  // ufix34
  wire [33:0] Root_Square12;  // ufix34
  reg [33:0] currentRoot_Square13_p;  // ufix34
  wire [1:0] constant_013;  // ufix2
  wire [35:0] prevRoot_Square_extend13;  // ufix36
  wire [1:0] constant_013_1;  // ufix2
  wire [18:0] prevRoot_extend13;  // ufix19
  wire [36:0] adder_add_temp_12;  // ufix37
  wire [36:0] adder_37;  // ufix37
  wire [36:0] adder_38;  // ufix37
  wire [35:0] Root_Square17_temp1;  // ufix36
  reg [65:0] resizedin13_p;  // ufix66
  wire [35:0] din_temp_13;  // ufix36
  wire relop_relop1_13;
  wire [17:0] Root_13;  // ufix18
  reg [17:0] currentRoot14_p;  // ufix18
  wire [35:0] Root_Square17_temp0;  // ufix36
  wire [35:0] Root_Square13;  // ufix36
  reg [35:0] currentRoot_Square14_p;  // ufix36
  wire [1:0] constant_014;  // ufix2
  wire [37:0] prevRoot_Square_extend14;  // ufix38
  wire [1:0] constant_014_1;  // ufix2
  wire [19:0] prevRoot_extend14;  // ufix20
  wire [38:0] adder_add_temp_13;  // ufix39
  wire [38:0] adder_40;  // ufix39
  wire [38:0] adder_41;  // ufix39
  wire [37:0] Root_Square18_temp1;  // ufix38
  reg [65:0] resizedin14_p;  // ufix66
  wire [37:0] din_temp_14;  // ufix38
  wire relop_relop1_14;
  wire [18:0] Root_14;  // ufix19
  reg [18:0] currentRoot15_p;  // ufix19
  wire [37:0] Root_Square18_temp0;  // ufix38
  wire [37:0] Root_Square14;  // ufix38
  reg [37:0] currentRoot_Square15_p;  // ufix38
  wire [1:0] constant_015;  // ufix2
  wire [39:0] prevRoot_Square_extend15;  // ufix40
  wire [1:0] constant_015_1;  // ufix2
  wire [20:0] prevRoot_extend15;  // ufix21
  wire [40:0] adder_add_temp_14;  // ufix41
  wire [40:0] adder_43;  // ufix41
  wire [40:0] adder_44;  // ufix41
  wire [39:0] Root_Square19_temp1;  // ufix40
  reg [65:0] resizedin15_p;  // ufix66
  wire [39:0] din_temp_15;  // ufix40
  wire relop_relop1_15;
  wire [19:0] Root_15;  // ufix20
  reg [19:0] currentRoot16_p;  // ufix20
  wire [39:0] Root_Square19_temp0;  // ufix40
  wire [39:0] Root_Square15;  // ufix40
  reg [39:0] currentRoot_Square16_p;  // ufix40
  wire [1:0] constant_016;  // ufix2
  wire [41:0] prevRoot_Square_extend16;  // ufix42
  wire [1:0] constant_016_1;  // ufix2
  wire [21:0] prevRoot_extend16;  // ufix22
  wire [42:0] adder_add_temp_15;  // ufix43
  wire [42:0] adder_46;  // ufix43
  wire [42:0] adder_47;  // ufix43
  wire [41:0] Root_Square20_temp1;  // ufix42
  reg [65:0] resizedin16_p;  // ufix66
  wire [41:0] din_temp_16;  // ufix42
  wire relop_relop1_16;
  wire [20:0] Root_16;  // ufix21
  reg [20:0] currentRoot17_p;  // ufix21
  wire [41:0] Root_Square20_temp0;  // ufix42
  wire [41:0] Root_Square16;  // ufix42
  reg [41:0] currentRoot_Square17_p;  // ufix42
  wire [1:0] constant_017;  // ufix2
  wire [43:0] prevRoot_Square_extend17;  // ufix44
  wire [1:0] constant_017_1;  // ufix2
  wire [22:0] prevRoot_extend17;  // ufix23
  wire [44:0] adder_add_temp_16;  // ufix45
  wire [44:0] adder_49;  // ufix45
  wire [44:0] adder_50;  // ufix45
  wire [43:0] Root_Square21_temp1;  // ufix44
  reg [65:0] resizedin17_p;  // ufix66
  wire [43:0] din_temp_17;  // ufix44
  wire relop_relop1_17;
  wire [21:0] Root_17;  // ufix22
  reg [21:0] currentRoot18_p;  // ufix22
  wire [43:0] Root_Square21_temp0;  // ufix44
  wire [43:0] Root_Square17;  // ufix44
  reg [43:0] currentRoot_Square18_p;  // ufix44
  wire [1:0] constant_018;  // ufix2
  wire [45:0] prevRoot_Square_extend18;  // ufix46
  wire [1:0] constant_018_1;  // ufix2
  wire [23:0] prevRoot_extend18;  // ufix24
  wire [46:0] adder_add_temp_17;  // ufix47
  wire [46:0] adder_52;  // ufix47
  wire [46:0] adder_53;  // ufix47
  wire [45:0] Root_Square22_temp1;  // ufix46
  reg [65:0] resizedin18_p;  // ufix66
  wire [45:0] din_temp_18;  // ufix46
  wire relop_relop1_18;
  wire [22:0] Root_18;  // ufix23
  reg [22:0] currentRoot19_p;  // ufix23
  wire [45:0] Root_Square22_temp0;  // ufix46
  wire [45:0] Root_Square18;  // ufix46
  reg [45:0] currentRoot_Square19_p;  // ufix46
  wire [1:0] constant_019;  // ufix2
  wire [47:0] prevRoot_Square_extend19;  // ufix48
  wire [1:0] constant_019_1;  // ufix2
  wire [24:0] prevRoot_extend19;  // ufix25
  wire [48:0] adder_add_temp_18;  // ufix49
  wire [48:0] adder_55;  // ufix49
  wire [48:0] adder_56;  // ufix49
  wire [47:0] Root_Square23_temp1;  // ufix48
  reg [65:0] resizedin19_p;  // ufix66
  wire [47:0] din_temp_19;  // ufix48
  wire relop_relop1_19;
  wire [23:0] Root_19;  // ufix24
  reg [23:0] currentRoot20_p;  // ufix24
  wire [47:0] Root_Square23_temp0;  // ufix48
  wire [47:0] Root_Square19;  // ufix48
  reg [47:0] currentRoot_Square20_p;  // ufix48
  wire [1:0] constant_020;  // ufix2
  wire [49:0] prevRoot_Square_extend20;  // ufix50
  wire [1:0] constant_020_1;  // ufix2
  wire [25:0] prevRoot_extend20;  // ufix26
  wire [50:0] adder_add_temp_19;  // ufix51
  wire [50:0] adder_58;  // ufix51
  wire [50:0] adder_59;  // ufix51
  wire [49:0] Root_Square24_temp1;  // ufix50
  reg [65:0] resizedin20_p;  // ufix66
  wire [49:0] din_temp_20;  // ufix50
  wire relop_relop1_20;
  wire [24:0] Root_20;  // ufix25
  reg [24:0] currentRoot21_p;  // ufix25
  wire [49:0] Root_Square24_temp0;  // ufix50
  wire [49:0] Root_Square20;  // ufix50
  reg [49:0] currentRoot_Square21_p;  // ufix50
  wire [1:0] constant_021;  // ufix2
  wire [51:0] prevRoot_Square_extend21;  // ufix52
  wire [1:0] constant_021_1;  // ufix2
  wire [26:0] prevRoot_extend21;  // ufix27
  wire [52:0] adder_add_temp_20;  // ufix53
  wire [52:0] adder_61;  // ufix53
  wire [52:0] adder_62;  // ufix53
  wire [51:0] Root_Square25_temp1;  // ufix52
  reg [65:0] resizedin21_p;  // ufix66
  wire [51:0] din_temp_21;  // ufix52
  wire relop_relop1_21;
  wire [25:0] Root_21;  // ufix26
  reg [25:0] currentRoot22_p;  // ufix26
  wire [51:0] Root_Square25_temp0;  // ufix52
  wire [51:0] Root_Square21;  // ufix52
  reg [51:0] currentRoot_Square22_p;  // ufix52
  wire [1:0] constant_022;  // ufix2
  wire [53:0] prevRoot_Square_extend22;  // ufix54
  wire [1:0] constant_022_1;  // ufix2
  wire [27:0] prevRoot_extend22;  // ufix28
  wire [54:0] adder_add_temp_21;  // ufix55
  wire [54:0] adder_64;  // ufix55
  wire [54:0] adder_65;  // ufix55
  wire [53:0] Root_Square26_temp1;  // ufix54
  reg [65:0] resizedin22_p;  // ufix66
  wire [53:0] din_temp_22;  // ufix54
  wire relop_relop1_22;
  wire [26:0] Root_22;  // ufix27
  reg [26:0] currentRoot23_p;  // ufix27
  reg [26:0] prevRoot_p2_reg [0:1];  // ufix27 [2]
  wire [26:0] prevRoot_p2_reg_next [0:1];  // ufix27 [2]
  wire [26:0] prevRoot_p_2;  // ufix27
  wire signed [32:0] outdata_1;  // sfix33_En18

  // Sqrt Implementation using Shift


  assign Root_Square4_temp1 = 10'b0000000001;



  assign resizedin = {20'b0, din[64:19]};



  assign resizedin_temp = resizedin;



  assign din_temp_0 = resizedin_temp[53:44];



  assign relop_relop1 = Root_Square4_temp1 <= din_temp_0;



  assign root_0_temp0 = 5'b00000;



  assign root_0_temp1 = 5'b00001;



  assign Root_0 = (relop_relop1 == 1'b0 ? root_0_temp0 :
              root_0_temp1);



  always @(posedge clk or posedge reset)
    begin : root_reg_process
      if (reset == 1'b1) begin
        currentRoot1_p <= 5'b00000;
      end
      else begin
        if (enb) begin
          currentRoot1_p <= Root_0;
        end
      end
    end



  assign Root_Square4_temp0 = 10'b0000000000;



  assign Root_Square0 = (relop_relop1 == 1'b0 ? Root_Square4_temp0 :
              Root_Square4_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_process
      if (reset == 1'b1) begin
        currentRoot_Square1_p <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square1_p <= Root_Square0;
        end
      end
    end



  assign constant_01 = 2'b01;



  assign prevRoot_Square_extend1 = {currentRoot_Square1_p, constant_01};



  assign constant_01_1 = 2'b00;



  assign prevRoot_extend1 = {currentRoot1_p, constant_01_1};



  assign adder_1 = {1'b0, prevRoot_Square_extend1};
  assign adder_2 = {6'b0, prevRoot_extend1};
  assign adder_add_temp = adder_1 + adder_2;
  assign Root_Square5_temp1 = (adder_add_temp[12] != 1'b0 ? 12'b111111111111 :
              adder_add_temp[11:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_process
      if (reset == 1'b1) begin
        resizedin1_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin1_p <= resizedin_temp;
        end
      end
    end



  assign din_temp_1 = resizedin1_p[53:42];



  assign relop_relop1_1 = Root_Square5_temp1 <= din_temp_1;



  assign Root_1 = {currentRoot1_p, relop_relop1_1};



  always @(posedge clk or posedge reset)
    begin : root_reg_1_process
      if (reset == 1'b1) begin
        currentRoot2_p <= 6'b000000;
      end
      else begin
        if (enb) begin
          currentRoot2_p <= Root_1;
        end
      end
    end



  assign Root_Square5_temp0 = {currentRoot_Square1_p, constant_01_1};



  assign Root_Square1 = (relop_relop1_1 == 1'b0 ? Root_Square5_temp0 :
              Root_Square5_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_1_process
      if (reset == 1'b1) begin
        currentRoot_Square2_p <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square2_p <= Root_Square1;
        end
      end
    end



  assign constant_02 = 2'b01;



  assign prevRoot_Square_extend2 = {currentRoot_Square2_p, constant_02};



  assign constant_02_1 = 2'b00;



  assign prevRoot_extend2 = {currentRoot2_p, constant_02_1};



  assign adder_4 = {1'b0, prevRoot_Square_extend2};
  assign adder_5 = {7'b0, prevRoot_extend2};
  assign adder_add_temp_1 = adder_4 + adder_5;
  assign Root_Square6_temp1 = (adder_add_temp_1[14] != 1'b0 ? 14'b11111111111111 :
              adder_add_temp_1[13:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_1_process
      if (reset == 1'b1) begin
        resizedin2_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin2_p <= resizedin1_p;
        end
      end
    end



  assign din_temp_2 = resizedin2_p[53:40];



  assign relop_relop1_2 = Root_Square6_temp1 <= din_temp_2;



  assign Root_2 = {currentRoot2_p, relop_relop1_2};



  always @(posedge clk or posedge reset)
    begin : root_reg_2_process
      if (reset == 1'b1) begin
        currentRoot3_p <= 7'b0000000;
      end
      else begin
        if (enb) begin
          currentRoot3_p <= Root_2;
        end
      end
    end



  assign Root_Square6_temp0 = {currentRoot_Square2_p, constant_02_1};



  assign Root_Square2 = (relop_relop1_2 == 1'b0 ? Root_Square6_temp0 :
              Root_Square6_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_2_process
      if (reset == 1'b1) begin
        currentRoot_Square3_p <= 14'b00000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square3_p <= Root_Square2;
        end
      end
    end



  assign constant_03 = 2'b01;



  assign prevRoot_Square_extend3 = {currentRoot_Square3_p, constant_03};



  assign constant_03_1 = 2'b00;



  assign prevRoot_extend3 = {currentRoot3_p, constant_03_1};



  assign adder_7 = {1'b0, prevRoot_Square_extend3};
  assign adder_8 = {8'b0, prevRoot_extend3};
  assign adder_add_temp_2 = adder_7 + adder_8;
  assign Root_Square7_temp1 = (adder_add_temp_2[16] != 1'b0 ? 16'b1111111111111111 :
              adder_add_temp_2[15:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_2_process
      if (reset == 1'b1) begin
        resizedin3_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin3_p <= resizedin2_p;
        end
      end
    end



  assign din_temp_3 = resizedin3_p[53:38];



  assign relop_relop1_3 = Root_Square7_temp1 <= din_temp_3;



  assign Root_3 = {currentRoot3_p, relop_relop1_3};



  always @(posedge clk or posedge reset)
    begin : root_reg_3_process
      if (reset == 1'b1) begin
        currentRoot4_p <= 8'b00000000;
      end
      else begin
        if (enb) begin
          currentRoot4_p <= Root_3;
        end
      end
    end



  assign Root_Square7_temp0 = {currentRoot_Square3_p, constant_03_1};



  assign Root_Square3 = (relop_relop1_3 == 1'b0 ? Root_Square7_temp0 :
              Root_Square7_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_3_process
      if (reset == 1'b1) begin
        currentRoot_Square4_p <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square4_p <= Root_Square3;
        end
      end
    end



  assign constant_04 = 2'b01;



  assign prevRoot_Square_extend4 = {currentRoot_Square4_p, constant_04};



  assign constant_04_1 = 2'b00;



  assign prevRoot_extend4 = {currentRoot4_p, constant_04_1};



  assign adder_10 = {1'b0, prevRoot_Square_extend4};
  assign adder_11 = {9'b0, prevRoot_extend4};
  assign adder_add_temp_3 = adder_10 + adder_11;
  assign Root_Square8_temp1 = (adder_add_temp_3[18] != 1'b0 ? 18'b111111111111111111 :
              adder_add_temp_3[17:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_3_process
      if (reset == 1'b1) begin
        resizedin4_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin4_p <= resizedin3_p;
        end
      end
    end



  assign din_temp_4 = resizedin4_p[53:36];



  assign relop_relop1_4 = Root_Square8_temp1 <= din_temp_4;



  assign Root_4 = {currentRoot4_p, relop_relop1_4};



  always @(posedge clk or posedge reset)
    begin : root_reg_4_process
      if (reset == 1'b1) begin
        currentRoot5_p <= 9'b000000000;
      end
      else begin
        if (enb) begin
          currentRoot5_p <= Root_4;
        end
      end
    end



  assign Root_Square8_temp0 = {currentRoot_Square4_p, constant_04_1};



  assign Root_Square4 = (relop_relop1_4 == 1'b0 ? Root_Square8_temp0 :
              Root_Square8_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_4_process
      if (reset == 1'b1) begin
        currentRoot_Square5_p <= 18'b000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square5_p <= Root_Square4;
        end
      end
    end



  assign constant_05 = 2'b01;



  assign prevRoot_Square_extend5 = {currentRoot_Square5_p, constant_05};



  assign constant_05_1 = 2'b00;



  assign prevRoot_extend5 = {currentRoot5_p, constant_05_1};



  assign adder_13 = {1'b0, prevRoot_Square_extend5};
  assign adder_14 = {10'b0, prevRoot_extend5};
  assign adder_add_temp_4 = adder_13 + adder_14;
  assign Root_Square9_temp1 = (adder_add_temp_4[20] != 1'b0 ? 20'b11111111111111111111 :
              adder_add_temp_4[19:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_4_process
      if (reset == 1'b1) begin
        resizedin5_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin5_p <= resizedin4_p;
        end
      end
    end



  assign din_temp_5 = resizedin5_p[53:34];



  assign relop_relop1_5 = Root_Square9_temp1 <= din_temp_5;



  assign Root_5 = {currentRoot5_p, relop_relop1_5};



  always @(posedge clk or posedge reset)
    begin : root_reg_5_process
      if (reset == 1'b1) begin
        currentRoot6_p <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          currentRoot6_p <= Root_5;
        end
      end
    end



  assign Root_Square9_temp0 = {currentRoot_Square5_p, constant_05_1};



  assign Root_Square5 = (relop_relop1_5 == 1'b0 ? Root_Square9_temp0 :
              Root_Square9_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_5_process
      if (reset == 1'b1) begin
        currentRoot_Square6_p <= 20'b00000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square6_p <= Root_Square5;
        end
      end
    end



  assign constant_06 = 2'b01;



  assign prevRoot_Square_extend6 = {currentRoot_Square6_p, constant_06};



  assign constant_06_1 = 2'b00;



  assign prevRoot_extend6 = {currentRoot6_p, constant_06_1};



  assign adder_16 = {1'b0, prevRoot_Square_extend6};
  assign adder_17 = {11'b0, prevRoot_extend6};
  assign adder_add_temp_5 = adder_16 + adder_17;
  assign Root_Square10_temp1 = (adder_add_temp_5[22] != 1'b0 ? 22'b1111111111111111111111 :
              adder_add_temp_5[21:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_5_process
      if (reset == 1'b1) begin
        resizedin6_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin6_p <= resizedin5_p;
        end
      end
    end



  assign din_temp_6 = resizedin6_p[53:32];



  assign relop_relop1_6 = Root_Square10_temp1 <= din_temp_6;



  assign Root_6 = {currentRoot6_p, relop_relop1_6};



  always @(posedge clk or posedge reset)
    begin : root_reg_6_process
      if (reset == 1'b1) begin
        currentRoot7_p <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          currentRoot7_p <= Root_6;
        end
      end
    end



  assign Root_Square10_temp0 = {currentRoot_Square6_p, constant_06_1};



  assign Root_Square6 = (relop_relop1_6 == 1'b0 ? Root_Square10_temp0 :
              Root_Square10_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_6_process
      if (reset == 1'b1) begin
        currentRoot_Square7_p <= 22'b0000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square7_p <= Root_Square6;
        end
      end
    end



  assign constant_07 = 2'b01;



  assign prevRoot_Square_extend7 = {currentRoot_Square7_p, constant_07};



  assign constant_07_1 = 2'b00;



  assign prevRoot_extend7 = {currentRoot7_p, constant_07_1};



  assign adder_19 = {1'b0, prevRoot_Square_extend7};
  assign adder_20 = {12'b0, prevRoot_extend7};
  assign adder_add_temp_6 = adder_19 + adder_20;
  assign Root_Square11_temp1 = (adder_add_temp_6[24] != 1'b0 ? 24'b111111111111111111111111 :
              adder_add_temp_6[23:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_6_process
      if (reset == 1'b1) begin
        resizedin7_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin7_p <= resizedin6_p;
        end
      end
    end



  assign din_temp_7 = resizedin7_p[53:30];



  assign relop_relop1_7 = Root_Square11_temp1 <= din_temp_7;



  assign Root_7 = {currentRoot7_p, relop_relop1_7};



  always @(posedge clk or posedge reset)
    begin : root_reg_7_process
      if (reset == 1'b1) begin
        currentRoot8_p <= 12'b000000000000;
      end
      else begin
        if (enb) begin
          currentRoot8_p <= Root_7;
        end
      end
    end



  assign Root_Square11_temp0 = {currentRoot_Square7_p, constant_07_1};



  assign Root_Square7 = (relop_relop1_7 == 1'b0 ? Root_Square11_temp0 :
              Root_Square11_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_7_process
      if (reset == 1'b1) begin
        currentRoot_Square8_p <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square8_p <= Root_Square7;
        end
      end
    end



  assign constant_08 = 2'b01;



  assign prevRoot_Square_extend8 = {currentRoot_Square8_p, constant_08};



  assign constant_08_1 = 2'b00;



  assign prevRoot_extend8 = {currentRoot8_p, constant_08_1};



  assign adder_22 = {1'b0, prevRoot_Square_extend8};
  assign adder_23 = {13'b0, prevRoot_extend8};
  assign adder_add_temp_7 = adder_22 + adder_23;
  assign Root_Square12_temp1 = (adder_add_temp_7[26] != 1'b0 ? 26'b11111111111111111111111111 :
              adder_add_temp_7[25:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_7_process
      if (reset == 1'b1) begin
        resizedin8_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin8_p <= resizedin7_p;
        end
      end
    end



  assign din_temp_8 = resizedin8_p[53:28];



  assign relop_relop1_8 = Root_Square12_temp1 <= din_temp_8;



  assign Root_8 = {currentRoot8_p, relop_relop1_8};



  always @(posedge clk or posedge reset)
    begin : root_reg_8_process
      if (reset == 1'b1) begin
        currentRoot9_p <= 13'b0000000000000;
      end
      else begin
        if (enb) begin
          currentRoot9_p <= Root_8;
        end
      end
    end



  assign Root_Square12_temp0 = {currentRoot_Square8_p, constant_08_1};



  assign Root_Square8 = (relop_relop1_8 == 1'b0 ? Root_Square12_temp0 :
              Root_Square12_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_8_process
      if (reset == 1'b1) begin
        currentRoot_Square9_p <= 26'b00000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square9_p <= Root_Square8;
        end
      end
    end



  assign constant_09 = 2'b01;



  assign prevRoot_Square_extend9 = {currentRoot_Square9_p, constant_09};



  assign constant_09_1 = 2'b00;



  assign prevRoot_extend9 = {currentRoot9_p, constant_09_1};



  assign adder_25 = {1'b0, prevRoot_Square_extend9};
  assign adder_26 = {14'b0, prevRoot_extend9};
  assign adder_add_temp_8 = adder_25 + adder_26;
  assign Root_Square13_temp1 = (adder_add_temp_8[28] != 1'b0 ? 28'b1111111111111111111111111111 :
              adder_add_temp_8[27:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_8_process
      if (reset == 1'b1) begin
        resizedin9_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin9_p <= resizedin8_p;
        end
      end
    end



  assign din_temp_9 = resizedin9_p[53:26];



  assign relop_relop1_9 = Root_Square13_temp1 <= din_temp_9;



  assign Root_9 = {currentRoot9_p, relop_relop1_9};



  always @(posedge clk or posedge reset)
    begin : root_reg_9_process
      if (reset == 1'b1) begin
        currentRoot10_p <= 14'b00000000000000;
      end
      else begin
        if (enb) begin
          currentRoot10_p <= Root_9;
        end
      end
    end



  assign Root_Square13_temp0 = {currentRoot_Square9_p, constant_09_1};



  assign Root_Square9 = (relop_relop1_9 == 1'b0 ? Root_Square13_temp0 :
              Root_Square13_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_9_process
      if (reset == 1'b1) begin
        currentRoot_Square10_p <= 28'b0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square10_p <= Root_Square9;
        end
      end
    end



  assign constant_010 = 2'b01;



  assign prevRoot_Square_extend10 = {currentRoot_Square10_p, constant_010};



  assign constant_010_1 = 2'b00;



  assign prevRoot_extend10 = {currentRoot10_p, constant_010_1};



  assign adder_28 = {1'b0, prevRoot_Square_extend10};
  assign adder_29 = {15'b0, prevRoot_extend10};
  assign adder_add_temp_9 = adder_28 + adder_29;
  assign Root_Square14_temp1 = (adder_add_temp_9[30] != 1'b0 ? 30'b111111111111111111111111111111 :
              adder_add_temp_9[29:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_9_process
      if (reset == 1'b1) begin
        resizedin10_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin10_p <= resizedin9_p;
        end
      end
    end



  assign din_temp_10 = resizedin10_p[53:24];



  assign relop_relop1_10 = Root_Square14_temp1 <= din_temp_10;



  assign Root_10 = {currentRoot10_p, relop_relop1_10};



  always @(posedge clk or posedge reset)
    begin : root_reg_10_process
      if (reset == 1'b1) begin
        currentRoot11_p <= 15'b000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot11_p <= Root_10;
        end
      end
    end



  assign Root_Square14_temp0 = {currentRoot_Square10_p, constant_010_1};



  assign Root_Square10 = (relop_relop1_10 == 1'b0 ? Root_Square14_temp0 :
              Root_Square14_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_10_process
      if (reset == 1'b1) begin
        currentRoot_Square11_p <= 30'b000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square11_p <= Root_Square10;
        end
      end
    end



  assign constant_011 = 2'b01;



  assign prevRoot_Square_extend11 = {currentRoot_Square11_p, constant_011};



  assign constant_011_1 = 2'b00;



  assign prevRoot_extend11 = {currentRoot11_p, constant_011_1};



  assign adder_31 = {1'b0, prevRoot_Square_extend11};
  assign adder_32 = {16'b0, prevRoot_extend11};
  assign adder_add_temp_10 = adder_31 + adder_32;
  assign Root_Square15_temp1 = (adder_add_temp_10[32] != 1'b0 ? 32'b11111111111111111111111111111111 :
              adder_add_temp_10[31:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_10_process
      if (reset == 1'b1) begin
        resizedin11_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin11_p <= resizedin10_p;
        end
      end
    end



  assign din_temp_11 = resizedin11_p[53:22];



  assign relop_relop1_11 = Root_Square15_temp1 <= din_temp_11;



  assign Root_11 = {currentRoot11_p, relop_relop1_11};



  always @(posedge clk or posedge reset)
    begin : root_reg_11_process
      if (reset == 1'b1) begin
        currentRoot12_p <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot12_p <= Root_11;
        end
      end
    end



  assign Root_Square15_temp0 = {currentRoot_Square11_p, constant_011_1};



  assign Root_Square11 = (relop_relop1_11 == 1'b0 ? Root_Square15_temp0 :
              Root_Square15_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_11_process
      if (reset == 1'b1) begin
        currentRoot_Square12_p <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square12_p <= Root_Square11;
        end
      end
    end



  assign constant_012 = 2'b01;



  assign prevRoot_Square_extend12 = {currentRoot_Square12_p, constant_012};



  assign constant_012_1 = 2'b00;



  assign prevRoot_extend12 = {currentRoot12_p, constant_012_1};



  assign adder_34 = {1'b0, prevRoot_Square_extend12};
  assign adder_35 = {17'b0, prevRoot_extend12};
  assign adder_add_temp_11 = adder_34 + adder_35;
  assign Root_Square16_temp1 = (adder_add_temp_11[34] != 1'b0 ? 34'h3FFFFFFFF :
              adder_add_temp_11[33:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_11_process
      if (reset == 1'b1) begin
        resizedin12_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin12_p <= resizedin11_p;
        end
      end
    end



  assign din_temp_12 = resizedin12_p[53:20];



  assign relop_relop1_12 = Root_Square16_temp1 <= din_temp_12;



  assign Root_12 = {currentRoot12_p, relop_relop1_12};



  always @(posedge clk or posedge reset)
    begin : root_reg_12_process
      if (reset == 1'b1) begin
        currentRoot13_p <= 17'b00000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot13_p <= Root_12;
        end
      end
    end



  assign Root_Square16_temp0 = {currentRoot_Square12_p, constant_012_1};



  assign Root_Square12 = (relop_relop1_12 == 1'b0 ? Root_Square16_temp0 :
              Root_Square16_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_12_process
      if (reset == 1'b1) begin
        currentRoot_Square13_p <= 34'h000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square13_p <= Root_Square12;
        end
      end
    end



  assign constant_013 = 2'b01;



  assign prevRoot_Square_extend13 = {currentRoot_Square13_p, constant_013};



  assign constant_013_1 = 2'b00;



  assign prevRoot_extend13 = {currentRoot13_p, constant_013_1};



  assign adder_37 = {1'b0, prevRoot_Square_extend13};
  assign adder_38 = {18'b0, prevRoot_extend13};
  assign adder_add_temp_12 = adder_37 + adder_38;
  assign Root_Square17_temp1 = (adder_add_temp_12[36] != 1'b0 ? 36'hFFFFFFFFF :
              adder_add_temp_12[35:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_12_process
      if (reset == 1'b1) begin
        resizedin13_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin13_p <= resizedin12_p;
        end
      end
    end



  assign din_temp_13 = resizedin13_p[53:18];



  assign relop_relop1_13 = Root_Square17_temp1 <= din_temp_13;



  assign Root_13 = {currentRoot13_p, relop_relop1_13};



  always @(posedge clk or posedge reset)
    begin : root_reg_13_process
      if (reset == 1'b1) begin
        currentRoot14_p <= 18'b000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot14_p <= Root_13;
        end
      end
    end



  assign Root_Square17_temp0 = {currentRoot_Square13_p, constant_013_1};



  assign Root_Square13 = (relop_relop1_13 == 1'b0 ? Root_Square17_temp0 :
              Root_Square17_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_13_process
      if (reset == 1'b1) begin
        currentRoot_Square14_p <= 36'h000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square14_p <= Root_Square13;
        end
      end
    end



  assign constant_014 = 2'b01;



  assign prevRoot_Square_extend14 = {currentRoot_Square14_p, constant_014};



  assign constant_014_1 = 2'b00;



  assign prevRoot_extend14 = {currentRoot14_p, constant_014_1};



  assign adder_40 = {1'b0, prevRoot_Square_extend14};
  assign adder_41 = {19'b0, prevRoot_extend14};
  assign adder_add_temp_13 = adder_40 + adder_41;
  assign Root_Square18_temp1 = (adder_add_temp_13[38] != 1'b0 ? 38'h3FFFFFFFFF :
              adder_add_temp_13[37:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_13_process
      if (reset == 1'b1) begin
        resizedin14_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin14_p <= resizedin13_p;
        end
      end
    end



  assign din_temp_14 = resizedin14_p[53:16];



  assign relop_relop1_14 = Root_Square18_temp1 <= din_temp_14;



  assign Root_14 = {currentRoot14_p, relop_relop1_14};



  always @(posedge clk or posedge reset)
    begin : root_reg_14_process
      if (reset == 1'b1) begin
        currentRoot15_p <= 19'b0000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot15_p <= Root_14;
        end
      end
    end



  assign Root_Square18_temp0 = {currentRoot_Square14_p, constant_014_1};



  assign Root_Square14 = (relop_relop1_14 == 1'b0 ? Root_Square18_temp0 :
              Root_Square18_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_14_process
      if (reset == 1'b1) begin
        currentRoot_Square15_p <= 38'h0000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square15_p <= Root_Square14;
        end
      end
    end



  assign constant_015 = 2'b01;



  assign prevRoot_Square_extend15 = {currentRoot_Square15_p, constant_015};



  assign constant_015_1 = 2'b00;



  assign prevRoot_extend15 = {currentRoot15_p, constant_015_1};



  assign adder_43 = {1'b0, prevRoot_Square_extend15};
  assign adder_44 = {20'b0, prevRoot_extend15};
  assign adder_add_temp_14 = adder_43 + adder_44;
  assign Root_Square19_temp1 = (adder_add_temp_14[40] != 1'b0 ? 40'hFFFFFFFFFF :
              adder_add_temp_14[39:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_14_process
      if (reset == 1'b1) begin
        resizedin15_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin15_p <= resizedin14_p;
        end
      end
    end



  assign din_temp_15 = resizedin15_p[53:14];



  assign relop_relop1_15 = Root_Square19_temp1 <= din_temp_15;



  assign Root_15 = {currentRoot15_p, relop_relop1_15};



  always @(posedge clk or posedge reset)
    begin : root_reg_15_process
      if (reset == 1'b1) begin
        currentRoot16_p <= 20'b00000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot16_p <= Root_15;
        end
      end
    end



  assign Root_Square19_temp0 = {currentRoot_Square15_p, constant_015_1};



  assign Root_Square15 = (relop_relop1_15 == 1'b0 ? Root_Square19_temp0 :
              Root_Square19_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_15_process
      if (reset == 1'b1) begin
        currentRoot_Square16_p <= 40'h0000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square16_p <= Root_Square15;
        end
      end
    end



  assign constant_016 = 2'b01;



  assign prevRoot_Square_extend16 = {currentRoot_Square16_p, constant_016};



  assign constant_016_1 = 2'b00;



  assign prevRoot_extend16 = {currentRoot16_p, constant_016_1};



  assign adder_46 = {1'b0, prevRoot_Square_extend16};
  assign adder_47 = {21'b0, prevRoot_extend16};
  assign adder_add_temp_15 = adder_46 + adder_47;
  assign Root_Square20_temp1 = (adder_add_temp_15[42] != 1'b0 ? 42'h3FFFFFFFFFF :
              adder_add_temp_15[41:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_15_process
      if (reset == 1'b1) begin
        resizedin16_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin16_p <= resizedin15_p;
        end
      end
    end



  assign din_temp_16 = resizedin16_p[53:12];



  assign relop_relop1_16 = Root_Square20_temp1 <= din_temp_16;



  assign Root_16 = {currentRoot16_p, relop_relop1_16};



  always @(posedge clk or posedge reset)
    begin : root_reg_16_process
      if (reset == 1'b1) begin
        currentRoot17_p <= 21'b000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot17_p <= Root_16;
        end
      end
    end



  assign Root_Square20_temp0 = {currentRoot_Square16_p, constant_016_1};



  assign Root_Square16 = (relop_relop1_16 == 1'b0 ? Root_Square20_temp0 :
              Root_Square20_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_16_process
      if (reset == 1'b1) begin
        currentRoot_Square17_p <= 42'h00000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square17_p <= Root_Square16;
        end
      end
    end



  assign constant_017 = 2'b01;



  assign prevRoot_Square_extend17 = {currentRoot_Square17_p, constant_017};



  assign constant_017_1 = 2'b00;



  assign prevRoot_extend17 = {currentRoot17_p, constant_017_1};



  assign adder_49 = {1'b0, prevRoot_Square_extend17};
  assign adder_50 = {22'b0, prevRoot_extend17};
  assign adder_add_temp_16 = adder_49 + adder_50;
  assign Root_Square21_temp1 = (adder_add_temp_16[44] != 1'b0 ? 44'hFFFFFFFFFFF :
              adder_add_temp_16[43:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_16_process
      if (reset == 1'b1) begin
        resizedin17_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin17_p <= resizedin16_p;
        end
      end
    end



  assign din_temp_17 = resizedin17_p[53:10];



  assign relop_relop1_17 = Root_Square21_temp1 <= din_temp_17;



  assign Root_17 = {currentRoot17_p, relop_relop1_17};



  always @(posedge clk or posedge reset)
    begin : root_reg_17_process
      if (reset == 1'b1) begin
        currentRoot18_p <= 22'b0000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot18_p <= Root_17;
        end
      end
    end



  assign Root_Square21_temp0 = {currentRoot_Square17_p, constant_017_1};



  assign Root_Square17 = (relop_relop1_17 == 1'b0 ? Root_Square21_temp0 :
              Root_Square21_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_17_process
      if (reset == 1'b1) begin
        currentRoot_Square18_p <= 44'h00000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square18_p <= Root_Square17;
        end
      end
    end



  assign constant_018 = 2'b01;



  assign prevRoot_Square_extend18 = {currentRoot_Square18_p, constant_018};



  assign constant_018_1 = 2'b00;



  assign prevRoot_extend18 = {currentRoot18_p, constant_018_1};



  assign adder_52 = {1'b0, prevRoot_Square_extend18};
  assign adder_53 = {23'b0, prevRoot_extend18};
  assign adder_add_temp_17 = adder_52 + adder_53;
  assign Root_Square22_temp1 = (adder_add_temp_17[46] != 1'b0 ? 46'h3FFFFFFFFFFF :
              adder_add_temp_17[45:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_17_process
      if (reset == 1'b1) begin
        resizedin18_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin18_p <= resizedin17_p;
        end
      end
    end



  assign din_temp_18 = resizedin18_p[53:8];



  assign relop_relop1_18 = Root_Square22_temp1 <= din_temp_18;



  assign Root_18 = {currentRoot18_p, relop_relop1_18};



  always @(posedge clk or posedge reset)
    begin : root_reg_18_process
      if (reset == 1'b1) begin
        currentRoot19_p <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot19_p <= Root_18;
        end
      end
    end



  assign Root_Square22_temp0 = {currentRoot_Square18_p, constant_018_1};



  assign Root_Square18 = (relop_relop1_18 == 1'b0 ? Root_Square22_temp0 :
              Root_Square22_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_18_process
      if (reset == 1'b1) begin
        currentRoot_Square19_p <= 46'h000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square19_p <= Root_Square18;
        end
      end
    end



  assign constant_019 = 2'b01;



  assign prevRoot_Square_extend19 = {currentRoot_Square19_p, constant_019};



  assign constant_019_1 = 2'b00;



  assign prevRoot_extend19 = {currentRoot19_p, constant_019_1};



  assign adder_55 = {1'b0, prevRoot_Square_extend19};
  assign adder_56 = {24'b0, prevRoot_extend19};
  assign adder_add_temp_18 = adder_55 + adder_56;
  assign Root_Square23_temp1 = (adder_add_temp_18[48] != 1'b0 ? 48'hFFFFFFFFFFFF :
              adder_add_temp_18[47:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_18_process
      if (reset == 1'b1) begin
        resizedin19_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin19_p <= resizedin18_p;
        end
      end
    end



  assign din_temp_19 = resizedin19_p[53:6];



  assign relop_relop1_19 = Root_Square23_temp1 <= din_temp_19;



  assign Root_19 = {currentRoot19_p, relop_relop1_19};



  always @(posedge clk or posedge reset)
    begin : root_reg_19_process
      if (reset == 1'b1) begin
        currentRoot20_p <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot20_p <= Root_19;
        end
      end
    end



  assign Root_Square23_temp0 = {currentRoot_Square19_p, constant_019_1};



  assign Root_Square19 = (relop_relop1_19 == 1'b0 ? Root_Square23_temp0 :
              Root_Square23_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_19_process
      if (reset == 1'b1) begin
        currentRoot_Square20_p <= 48'h000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square20_p <= Root_Square19;
        end
      end
    end



  assign constant_020 = 2'b01;



  assign prevRoot_Square_extend20 = {currentRoot_Square20_p, constant_020};



  assign constant_020_1 = 2'b00;



  assign prevRoot_extend20 = {currentRoot20_p, constant_020_1};



  assign adder_58 = {1'b0, prevRoot_Square_extend20};
  assign adder_59 = {25'b0, prevRoot_extend20};
  assign adder_add_temp_19 = adder_58 + adder_59;
  assign Root_Square24_temp1 = (adder_add_temp_19[50] != 1'b0 ? 50'h3FFFFFFFFFFFF :
              adder_add_temp_19[49:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_19_process
      if (reset == 1'b1) begin
        resizedin20_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin20_p <= resizedin19_p;
        end
      end
    end



  assign din_temp_20 = resizedin20_p[53:4];



  assign relop_relop1_20 = Root_Square24_temp1 <= din_temp_20;



  assign Root_20 = {currentRoot20_p, relop_relop1_20};



  always @(posedge clk or posedge reset)
    begin : root_reg_20_process
      if (reset == 1'b1) begin
        currentRoot21_p <= 25'b0000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot21_p <= Root_20;
        end
      end
    end



  assign Root_Square24_temp0 = {currentRoot_Square20_p, constant_020_1};



  assign Root_Square20 = (relop_relop1_20 == 1'b0 ? Root_Square24_temp0 :
              Root_Square24_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_20_process
      if (reset == 1'b1) begin
        currentRoot_Square21_p <= 50'h0000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square21_p <= Root_Square20;
        end
      end
    end



  assign constant_021 = 2'b01;



  assign prevRoot_Square_extend21 = {currentRoot_Square21_p, constant_021};



  assign constant_021_1 = 2'b00;



  assign prevRoot_extend21 = {currentRoot21_p, constant_021_1};



  assign adder_61 = {1'b0, prevRoot_Square_extend21};
  assign adder_62 = {26'b0, prevRoot_extend21};
  assign adder_add_temp_20 = adder_61 + adder_62;
  assign Root_Square25_temp1 = (adder_add_temp_20[52] != 1'b0 ? 52'hFFFFFFFFFFFFF :
              adder_add_temp_20[51:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_20_process
      if (reset == 1'b1) begin
        resizedin21_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin21_p <= resizedin20_p;
        end
      end
    end



  assign din_temp_21 = resizedin21_p[53:2];



  assign relop_relop1_21 = Root_Square25_temp1 <= din_temp_21;



  assign Root_21 = {currentRoot21_p, relop_relop1_21};



  always @(posedge clk or posedge reset)
    begin : root_reg_21_process
      if (reset == 1'b1) begin
        currentRoot22_p <= 26'b00000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot22_p <= Root_21;
        end
      end
    end



  assign Root_Square25_temp0 = {currentRoot_Square21_p, constant_021_1};



  assign Root_Square21 = (relop_relop1_21 == 1'b0 ? Root_Square25_temp0 :
              Root_Square25_temp1);



  always @(posedge clk or posedge reset)
    begin : root_sq_p_reg_21_process
      if (reset == 1'b1) begin
        currentRoot_Square22_p <= 52'h0000000000000;
      end
      else begin
        if (enb) begin
          currentRoot_Square22_p <= Root_Square21;
        end
      end
    end



  assign constant_022 = 2'b01;



  assign prevRoot_Square_extend22 = {currentRoot_Square22_p, constant_022};



  assign constant_022_1 = 2'b00;



  assign prevRoot_extend22 = {currentRoot22_p, constant_022_1};



  assign adder_64 = {1'b0, prevRoot_Square_extend22};
  assign adder_65 = {27'b0, prevRoot_extend22};
  assign adder_add_temp_21 = adder_64 + adder_65;
  assign Root_Square26_temp1 = (adder_add_temp_21[54] != 1'b0 ? 54'h3FFFFFFFFFFFFF :
              adder_add_temp_21[53:0]);



  always @(posedge clk or posedge reset)
    begin : resizedin_reg_21_process
      if (reset == 1'b1) begin
        resizedin22_p <= 66'h00000000000000000;
      end
      else begin
        if (enb) begin
          resizedin22_p <= resizedin21_p;
        end
      end
    end



  assign din_temp_22 = resizedin22_p[53:0];



  assign relop_relop1_22 = Root_Square26_temp1 <= din_temp_22;



  assign Root_22 = {currentRoot22_p, relop_relop1_22};



  always @(posedge clk or posedge reset)
    begin : root_reg_22_process
      if (reset == 1'b1) begin
        currentRoot23_p <= 27'b000000000000000000000000000;
      end
      else begin
        if (enb) begin
          currentRoot23_p <= Root_22;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : prevRoot_p2_process
      if (reset == 1'b1) begin
        prevRoot_p2_reg[0] <= 27'b000000000000000000000000000;
        prevRoot_p2_reg[1] <= 27'b000000000000000000000000000;
      end
      else begin
        if (enb) begin
          prevRoot_p2_reg[0] <= prevRoot_p2_reg_next[0];
          prevRoot_p2_reg[1] <= prevRoot_p2_reg_next[1];
        end
      end
    end

  assign prevRoot_p_2 = prevRoot_p2_reg[1];
  assign prevRoot_p2_reg_next[0] = currentRoot23_p;
  assign prevRoot_p2_reg_next[1] = prevRoot_p2_reg[0];



  assign outdata_1 = {6'b0, prevRoot_p_2};



  assign dout = outdata_1;

endmodule  // Sqrt

